import { useCallback, useEffect, useMemo, useState } from "react";
import { Flag, MessageSquareReply, ShieldCheck, ThumbsUp } from "lucide-react";
import { Link } from "react-router-dom";
import { RelatedDiscussionList } from "@/components/community/RelatedDiscussionList";
import { projectCommunityApi, type ProjectComment } from "@/lib/api/project-community";

export function ProjectDiscussion({ projectId, signedIn }: { projectId: string; signedIn: boolean }) {
  const [items, setItems] = useState<ProjectComment[]>([]); const [body, setBody] = useState(""); const [replyTo, setReplyTo] = useState<ProjectComment | null>(null);
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const refresh = useCallback(async () => setItems(await projectCommunityApi.listComments(projectId)), [projectId]);
  useEffect(() => { void refresh().catch((cause) => setError(cause instanceof Error ? cause.message : "Discussion is unavailable.")); }, [refresh]);
  const roots = useMemo(() => items.filter((item) => !item.parentId), [items]);
  const replies = useMemo(() => { const map = new Map<string, ProjectComment[]>(); for (const item of items) if (item.parentId) map.set(item.parentId, [...(map.get(item.parentId) ?? []), item]); return map; }, [items]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(null); try { await projectCommunityApi.createComment(projectId, { body, parentId: replyTo?.id ?? null }); setBody(""); setReplyTo(null); setMessage("Comment published"); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Comment could not be published."); } finally { setBusy(false); } };
  const helpful = async (comment: ProjectComment) => { try { const result = await projectCommunityApi.markHelpful(projectId, comment.id); setItems((current) => current.map((item) => item.id === comment.id ? { ...item, ...result } : item)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Reaction could not be saved."); } };
  const report = async (comment: ProjectComment) => { try { await projectCommunityApi.report({ entityType: "comment", entityId: comment.id, reason: "other", details: "Flagged from the project discussion surface for moderator assessment." }); setMessage("Report submitted for moderation"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Report could not be submitted."); } };

  return <div className="space-y-3">
    <section className="surface-card p-4"><h2 className="font-semibold">Project discussion</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">Ask project-local technical questions or reply once. Long-form engineering threads remain in the forum below.</p>{signedIn ? <form onSubmit={(event) => void submit(event)} className="mt-3"><label className="block text-xs"><span className="section-title">{replyTo ? `Reply to ${replyTo.authorName}` : "New comment"}</span><textarea required minLength={2} maxLength={4000} value={body} onChange={(event) => setBody(event.target.value)} className="input-bare mt-1 min-h-24 w-full" /></label><div className="mt-2 flex justify-end gap-2">{replyTo && <button type="button" onClick={() => setReplyTo(null)} className="btn-ghost">Cancel reply</button>}<button disabled={busy} className="btn-primary">{busy ? "Publishing…" : replyTo ? "Publish reply" : "Publish comment"}</button></div></form> : <Link to="/auth?redirect=discussion" className="btn-primary mt-3 inline-flex">Sign in to comment</Link>}{message && <p role="status" className="mt-2 text-xs text-positive">{message}</p>}{error && <p role="alert" className="mt-2 text-xs text-negative">{error}</p>}</section>
    <section className="surface-card overflow-hidden"><div className="border-b border-border px-4 py-3"><h2 className="section-title">Comments · {items.length}</h2></div>{roots.length ? <div className="divide-y divide-border">{roots.map((comment) => <div key={comment.id} className="p-4"><Comment item={comment} signedIn={signedIn} onReply={() => setReplyTo(comment)} onHelpful={() => void helpful(comment)} onReport={() => void report(comment)} />{(replies.get(comment.id) ?? []).map((reply) => <div key={reply.id} className="ml-4 mt-3 border-l-2 border-primary/30 pl-3 sm:ml-8"><Comment item={reply} signedIn={signedIn} onHelpful={() => void helpful(reply)} onReport={() => void report(reply)} /></div>)}</div>)}</div> : <p className="p-4 text-xs text-muted-foreground">No project-local comments yet.</p>}</section>
    <RelatedDiscussionList relatedType="project" relatedId={projectId} title="Related forum threads" />
  </div>;
}
function Comment({ item, signedIn, onReply, onHelpful, onReport }: { item: ProjectComment; signedIn: boolean; onReply?: () => void; onHelpful: () => void; onReport: () => void }) { return <article><div className="flex flex-wrap items-center gap-2 text-[10.5px] text-muted-foreground"><span className="font-medium text-foreground">{item.authorName}</span>{item.experienceBadges.map((badge) => <span key={badge.badgeType} className="pill pill-good inline-flex items-center gap-1"><ShieldCheck className="h-3 w-3" /> verified {badge.badgeType.replaceAll("_", " ")}</span>)}<time dateTime={item.createdAt}>{new Date(item.createdAt).toLocaleString()}</time></div><p className="mt-2 whitespace-pre-wrap text-xs leading-6">{item.body}</p>{signedIn && <div className="mt-2 flex flex-wrap gap-1"><button onClick={onHelpful} className={item.helpfulByMe ? "btn-primary btn-sm" : "btn-ghost btn-sm"}><ThumbsUp className="h-3.5 w-3.5" /> Helpful {item.helpfulCount || ""}</button>{onReply && <button onClick={onReply} className="btn-ghost btn-sm"><MessageSquareReply className="h-3.5 w-3.5" /> Reply</button>}<button onClick={onReport} className="btn-ghost btn-sm text-muted-foreground"><Flag className="h-3.5 w-3.5" /> Report</button></div>}</article>; }
