import { useCallback, useEffect, useState } from "react";
import { Flag, ShieldCheck, Star } from "lucide-react";
import { Link } from "react-router-dom";
import { projectCommunityApi, type ProjectReview, type ProjectReviewInput, type ProjectReviewAggregate } from "@/lib/api/project-community";

const emptyAggregate: ProjectReviewAggregate = { count: 0, overallAverage: null, reliabilityAverage: null, usabilityAverage: null, valueAverage: null, supportAverage: null };
const initial: ProjectReviewInput = { overallRating: 5, reliabilityRating: null, usabilityRating: null, valueRating: null, supportRating: null, relationship: "observer", title: "", body: "" };

export function ProjectReviews({ projectId, signedIn }: { projectId: string; signedIn: boolean }) {
  const [items, setItems] = useState<ProjectReview[]>([]); const [aggregate, setAggregate] = useState(emptyAggregate);
  const [form, setForm] = useState(initial); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const refresh = useCallback(async () => { const result = await projectCommunityApi.listReviews(projectId); setItems(result.items); setAggregate(result.aggregate); }, [projectId]);
  useEffect(() => { void refresh().catch((cause) => setError(cause instanceof Error ? cause.message : "Reviews are unavailable.")); }, [refresh]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(null); try { const review = await projectCommunityApi.upsertReview(projectId, form); setMessage(review.editCount ? "Review updated" : "Review published"); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Review could not be saved."); } finally { setBusy(false); } };
  const report = async (review: ProjectReview) => { try { await projectCommunityApi.report({ entityType: "review", entityId: review.id, reason: "other", details: "Flagged from the project review surface for moderator assessment." }); setMessage("Report submitted for moderation"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Report could not be submitted."); } };

  return <div className="space-y-3">
    <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3"><Metric label="Overall rating" value={aggregate.overallAverage == null ? "No reviews" : `${aggregate.overallAverage.toFixed(1)} / 5`} /><Metric label="Published reviews" value={String(aggregate.count)} /><Metric label="Reliability" value={average(aggregate.reliabilityAverage)} /></div>
    <section className="surface-card p-4"><h2 className="font-semibold">Write or update your review</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">One review per signed-in user and project. Edits update the same review and preserve revision history.</p>{signedIn ? <form onSubmit={(event) => void submit(event)} className="mt-3 space-y-3"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3"><Rating label="Overall rating" value={form.overallRating} onChange={(value) => setForm({ ...form, overallRating: value })} required /><Rating label="Reliability rating" value={form.reliabilityRating} onChange={(value) => setForm({ ...form, reliabilityRating: value })} /><label className="text-xs"><span className="section-title">Relationship</span><select value={form.relationship} onChange={(event) => setForm({ ...form, relationship: event.target.value as ProjectReviewInput["relationship"] })} className="input-bare mt-1 h-10 w-full"><option value="observer">Observer</option><option value="evaluator">Evaluator</option><option value="operator">Operator, unverified</option><option value="owner">Owner, unverified</option></select></label></div><label className="block text-xs"><span className="section-title">Review title</span><input required minLength={5} maxLength={200} value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} className="input-bare mt-1 h-10 w-full" /></label><label className="block text-xs"><span className="section-title">Substantive review</span><textarea required minLength={50} maxLength={5000} value={form.body} onChange={(event) => setForm({ ...form, body: event.target.value })} className="input-bare mt-1 min-h-28 w-full" /></label><div className="flex justify-end"><button disabled={busy} className="btn-primary">{busy ? "Saving…" : "Publish review"}</button></div></form> : <Link to="/auth?redirect=review" className="btn-primary mt-3 inline-flex">Sign in to review</Link>}{message && <p role="status" className="mt-3 text-xs text-positive">{message}</p>}{error && <p role="alert" className="mt-3 text-xs text-negative">{error}</p>}</section>
    <section className="surface-card overflow-hidden"><div className="border-b border-border px-4 py-3"><h2 className="section-title">Published reviews · {items.length}</h2></div>{items.length ? <div className="divide-y divide-border">{items.map((review) => <article key={review.id} className="p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><div className="flex items-center gap-2"><span className="font-semibold">{review.title}</span><span className="inline-flex items-center gap-1 font-mono text-xs"><Star className="h-3.5 w-3.5 fill-primary text-primary" />{review.overallRating}/5</span></div><div className="mt-1 flex flex-wrap items-center gap-2 text-[10.5px] text-muted-foreground"><span>{review.authorName}</span><span>{review.relationship}</span>{review.experienceBadges.map((badge) => <span key={badge.badgeType} className="pill pill-good inline-flex items-center gap-1"><ShieldCheck className="h-3 w-3" /> verified {badge.badgeType.replaceAll("_", " ")}</span>)}<span>edited {review.editCount}×</span></div></div>{signedIn && <button onClick={() => void report(review)} className="btn-ghost btn-sm text-muted-foreground"><Flag className="h-3.5 w-3.5" /> Report</button>}</div><p className="mt-3 whitespace-pre-wrap text-xs leading-6 text-muted-foreground">{review.body}</p></article>)}</div> : <p className="p-4 text-xs text-muted-foreground">No published reviews. Fake seed ratings are never shown.</p>}</section>
  </div>;
}
function Rating({ label, value, onChange, required = false }: { label: string; value: number | null; onChange: (value: number | null) => void; required?: boolean }) { return <label className="text-xs"><span className="section-title">{label}</span><select value={value ?? ""} required={required} onChange={(event) => onChange(event.target.value ? Number(event.target.value) : null)} className="input-bare mt-1 h-10 w-full">{!required && <option value="">Not rated</option>}{[5,4,3,2,1].map((rating) => <option key={rating} value={rating}>{rating} / 5</option>)}</select></label>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="surface-card p-3"><div className="section-title">{label}</div><div className="mt-1 font-mono text-lg font-bold">{value}</div></div>; }
function average(value: number | null) { return value == null ? "Not rated" : `${value.toFixed(1)} / 5`; }
