import { useState } from "react";
import { Link } from "react-router-dom";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { MessageCircle, UserPlus, Users } from "lucide-react";
import { toast } from "@/hooks/use-toast";
import { projectSystemsApi } from "@/lib/api/systems";

const roles = ["maintainer", "editor", "reviewer", "builder", "viewer"] as const;
export function ProjectPeoplePanel({ projectId, organizationId, canManage }: { projectId: string; organizationId?: string | null; canManage: boolean }) { const client = useQueryClient(); const [open, setOpen] = useState(false); const [username, setUsername] = useState(""); const [role, setRole] = useState<(typeof roles)[number]>("viewer"); const [busy, setBusy] = useState(false); const people = useQuery({ queryKey: ["project-collaborators", projectId], queryFn: ({ signal }) => projectSystemsApi.collaborators(projectId, signal), retry: false }); const invite = async () => { setBusy(true); try { await projectSystemsApi.inviteCollaborator(projectId, username, role); setUsername(""); setOpen(false); await client.invalidateQueries({ queryKey: ["project-collaborators", projectId] }); toast({ title: "Project invitation sent" }); } catch (error) { toast({ title: "Invitation failed", description: error instanceof Error ? error.message : String(error), variant: "destructive" }); } finally { setBusy(false); } };
  return <section className="surface-card p-3"><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2"><Users className="h-4 w-4 text-primary" /><div><h2 className="text-[13px] font-semibold">Associated people</h2><p className="text-[10px] text-muted-foreground">Owners, maintainers, reviewers, editors, and builders</p></div></div>{canManage && <button onClick={() => setOpen((value) => !value)} className="btn-ghost btn-sm min-h-10"><UserPlus className="h-3.5 w-3.5" /> Invite</button>}</div>{organizationId && <p className="mt-2 rounded bg-muted px-2 py-1 text-[10px]">Organization project · {organizationId}</p>}{open && <div className="mt-3 rounded border border-border p-2"><input value={username} onChange={(event) => setUsername(event.target.value)} placeholder="Username" className="input-bare min-h-10 w-full" /><select value={role} onChange={(event) => setRole(event.target.value as typeof role)} className="input-bare mt-2 min-h-10 w-full">{roles.map((item) => <option key={item} value={item}>{item}</option>)}</select><button disabled={busy || username.trim().length < 2} onClick={() => void invite()} className="btn-primary btn-sm mt-2 min-h-10 disabled:opacity-50">Send invitation</button></div>}<div className="mt-3 space-y-2">{people.data?.items.map((person) => <div key={String(person.user_id)} className="flex items-center justify-between gap-2 rounded border border-border p-2"><div className="min-w-0"><div className="truncate text-xs font-medium">{String(person.display_name ?? person.username ?? "RoboPartPicker user")}</div><div className="text-[10px] text-muted-foreground">{String(person.role)} · {String(person.status)}</div></div>{person.contactAllowed !== false && person.user_id && <Link to={`/messages?to=${encodeURIComponent(String(person.user_id))}&context=project&contextId=${encodeURIComponent(projectId)}`} aria-label={`Message ${String(person.display_name ?? person.username ?? "user")}`} className="btn-ghost min-h-10 min-w-10 p-2"><MessageCircle className="h-4 w-4" /></Link>}</div>)}{people.data?.items.length === 0 && <p className="text-[11px] text-muted-foreground">No associated users are visible.</p>}</div></section>; }
