const fs = require('fs');
const path = '.agent-planning/rehearsal/reports/U-008-v4-pass1-replacement.json';
const j = JSON.parse(fs.readFileSync(path, 'utf8'));
const req = ['unit_id','pass','executable','blocking_questions','missing_context','ambiguous_steps','false_completion_paths','scope_escape_risks','unsafe_assumptions','defects','exact_inputs_named','allowed_writes_named','commands_named','completion_evidence_named','review_handoff_named','stop_conditions_named','what_i_did_not_check','confidence'];
const missing = req.filter(k => !(k in j));
const defectKeys = j.defects.length ? Object.keys(j.defects[0]) : [];
const defRequired = ['defect_id','severity','unit_id','evidence','consequence','proposed_resolution'];
const defMissing = defRequired.filter(k => !defectKeys.includes(k));
const defSeverities = j.defects.map(d => d.severity);
const allowedSev = ['P0','P1','P2','P3'];
const badSev = defSeverities.filter(s => !allowedSev.includes(s));
console.log('TOP_LEVEL_KEYS_OK=' + (missing.length === 0));
console.log('MISSING_TOP=' + JSON.stringify(missing));
console.log('DEFECT_KEYS=' + JSON.stringify(defectKeys));
console.log('DEFECT_MISSING=' + JSON.stringify(defMissing));
console.log('DEFECT_COUNT=' + j.defects.length);
console.log('BAD_SEVERITIES=' + JSON.stringify(badSev));
console.log('EXECUTABLE=' + j.executable);
console.log('CONFIDENCE=' + j.confidence);
console.log('UNIT_ID=' + j.unit_id);
console.log('PASS=' + j.pass);
console.log('TOP_LEVEL_KEYS_PRESENT=' + Object.keys(j).length);
console.log('BLOCKING_Q_COUNT=' + j.blocking_questions.length);
console.log('MISSING_CTX_COUNT=' + j.missing_context.length);
console.log('AMBIG_STEPS_COUNT=' + j.ambiguous_steps.length);
console.log('FALSE_PATHS_COUNT=' + j.false_completion_paths.length);
console.log('SCOPE_RISKS_COUNT=' + j.scope_escape_risks.length);
console.log('UNSAFE_ASSUMP_COUNT=' + j.unsafe_assumptions.length);
console.log('NOT_CHECKED_COUNT=' + j.what_i_did_not_check.length);
