export type MarketplaceListing = {
  id: string;
  slug: string;
  sellerUserId: string | null;
  organizationId: string | null;
  listingType: "sell" | "wanted" | "service";
  title: string;
  description: string;
  category: string;
  conditionGrade: "A" | "B" | "C" | "untested" | "for_parts" | "not_applicable" | null;
  currency: string | null;
  price: number | null;
  quantity: number;
  region: string | null;
  status: "draft" | "published" | "reserved" | "sold" | "fulfilled" | "expired" | "withdrawn" | "removed";
  visibility: "private" | "organization" | "unlisted" | "public";
  sourceBuildId: string | null;
  sourceComponentId: string | null;
  expiresAt: string | null;
  version: number;
  isDemo: boolean;
  createdAt: string;
  updatedAt: string;
  publishedAt: string | null;
  seller: { id: string; displayName: string | null; username: string | null; avatarUrl: string | null } | null;
  component: { id: string; slug: string; name: string; category: string } | null;
  details: {
    runtimeHours: number | null;
    provenanceText: string | null;
    sellerDeclaresTestReport: boolean;
    sellerDeclaresVideo: boolean;
    sellerAcceptsReturns: boolean;
    serialAvailable: boolean;
  };
  saved: boolean;
};

export type MarketplaceListingInput = {
  listingType: MarketplaceListing["listingType"];
  title: string;
  description: string;
  category: string;
  conditionGrade?: MarketplaceListing["conditionGrade"];
  currency?: string | null;
  price?: number | null;
  quantity: number;
  region?: string | null;
  visibility: MarketplaceListing["visibility"];
  organizationId?: string | null;
  sourceBuildId?: string | null;
  sourceComponentId?: string | null;
  expiresAt?: string | null;
  runtimeHours?: number | null;
  provenanceText?: string | null;
  sellerDeclaresTestReport?: boolean;
  sellerDeclaresVideo?: boolean;
  sellerAcceptsReturns?: boolean;
  serialAvailable?: boolean;
};
