import { Hono } from "hono";
import { z } from "zod";
import type { AppBindings } from "../env";
import { ProjectsRepository } from "../db/repositories/projects";
import { BuildsRepository } from "../db/repositories/builds";
import { AppError } from "../http";
import { loadAuthSession, requireAuth } from "../middleware/authentication";
import { assertScopedRead, assertScopedWrite, authenticatedUserId, requirePlatformRole } from "../middleware/authorization";
import { recordAuditEvent } from "../services/audit";
import { parseJson } from "../validation";

const analyticsTypeSchema = z.enum(["view", "save", "fork", "build_start", "build_complete", "verified_reproduction", "bom_export", "rpps_export", "marketplace_referral", "question", "missing_information_request", "version_adoption", "substitution"]);
const analyticsSchema = z.object({ eventType: analyticsTypeSchema, sessionId: z.string().trim().min(8).max(160).optional(), metadata: z.record(z.string(), z.unknown()).default({}) }).strict();
const partOutCreateSchema = z.object({ sourceListingId: z.string().uuid().optional(), sourceProjectId: z.string().uuid().optional(), sourceBuildId: z.string().uuid().optional(), sourceBomVersionId: z.string().uuid().optional(), currency: z.string().length(3).transform((value) => value.toUpperCase()).default("USD") }).strict().refine((value) => value.sourceBuildId || value.sourceBomVersionId, "A build or BOM version is required.");
const partOutItemSchema = z.object({ presenceStatus: z.enum(["unconfirmed", "present", "missing", "modified", "damaged", "fabricated", "unidentifiable", "sold", "excluded"]), conditionGrade: z.string().trim().max(50).nullable().optional(), testEvidence: z.array(z.record(z.string(), z.unknown())).max(100).default([]), pricing: z.record(z.string(), z.unknown()).default({}) }).strict();
const estimateSchema = z.object({ estimatedFeeRate: z.number().min(0).max(1).default(0.13), shippingComplexity: z.enum(["low", "medium", "high", "freight"]).default("medium"), ageAssumptionYears: z.number().min(0).max(100).nullable().optional(), notes: z.string().trim().max(2_000).optional() }).strict();
const bundleSchema = z.object({ name: z.string().trim().min(2).max(200), rationale: z.string().trim().max(2_000).optional(), itemIds: z.array(z.string().uuid()).min(1).max(100), pricing: z.record(z.string(), z.unknown()).default({}) }).strict();
const draftListingsSchema = z.object({ itemIds: z.array(z.string().uuid()).max(500).default([]), bundleIds: z.array(z.string().uuid()).max(100).default([]) }).strict().refine((value) => value.itemIds.length > 0 || value.bundleIds.length > 0, "Select at least one item or bundle.");
const operationsCaseSchema = z.object({ caseType: z.enum(["duplicate_component", "data_conflict", "canonical_merge", "project_ownership", "community_moderation", "marketplace_moderation", "user_report", "messaging_abuse", "ai_friction", "failed_job", "appeal", "bom_verification"]), sourceEntityType: z.string().trim().max(100).optional(), sourceEntityId: z.string().trim().max(200).optional(), title: z.string().trim().min(2).max(300), summary: z.string().trim().max(4_000).optional(), priority: z.enum(["low", "medium", "high", "critical"]).default("medium") }).strict();
const operationsUpdateSchema = z.object({ status: z.enum(["open", "triaged", "assigned", "investigating", "resolved", "dismissed", "appealed"]), priority: z.enum(["low", "medium", "high", "critical"]).optional(), assignedToUserId: z.string().uuid().nullable().optional(), resolution: z.string().trim().max(4_000).optional() }).strict();
const frictionClusterSchema = z.object({ title: z.string().trim().min(2).max(300), description: z.string().trim().max(4_000).optional(), feature: z.string().trim().max(120).optional(), priority: z.enum(["low", "medium", "high", "critical"]).default("medium"), eventIds: z.array(z.string().uuid()).min(1).max(500), assignedToUserId: z.string().uuid().nullable().optional() }).strict();

export const marketplaceAnalyticsOperationsRoutes = new Hono<AppBindings>();

marketplaceAnalyticsOperationsRoutes.post("/projects/:id/analytics/events", loadAuthSession, async (c) => {
  const project = await new ProjectsRepository(c.env.DB).find(c.req.param("id")); if (!project) throw new AppError(404, "PROJECT_NOT_FOUND", "Project not found."); await assertScopedRead(c.env.DB, c.get("authSession")?.user?.id ?? null, project.row);
  const body = await parseJson(c, analyticsSchema); const userId = c.get("authSession")?.user?.id ?? null;
  if (userId) { const preference = await c.env.DB.prepare("SELECT analytics_opt_out FROM user_preferences WHERE user_id = ?1").bind(userId).first<{ analytics_opt_out: number }>(); if (preference?.analytics_opt_out === 1) return c.json({ recorded: false, reason: "opted_out" }); }
  const now = new Date(); const day = now.toISOString().slice(0, 10); const actorHash = userId ? await hash(`${day}:user:${userId}`) : null; const sessionHash = body.sessionId ? await hash(`${day}:session:${body.sessionId}`) : null;
  const sourceCategory = categorizeReferrer(c.req.header("referer")); const country = countryCode(c.req.raw);
  const uniqueKey = actorHash ?? sessionHash; const existing = uniqueKey ? await c.env.DB.prepare(`SELECT 1 AS seen FROM project_analytics_events WHERE project_id = ?1 AND event_type = ?2
    AND occurred_at >= ?3 AND (actor_user_hash = ?4 OR session_hash = ?4) LIMIT 1`).bind(project.row.id, body.eventType, `${day}T00:00:00.000Z`, uniqueKey).first() : null;
  const prior = uniqueKey ? await c.env.DB.prepare(`SELECT 1 AS seen FROM project_analytics_events WHERE project_id = ?1
    AND occurred_at < ?2 AND (actor_user_hash = ?3 OR session_hash = ?3) LIMIT 1`).bind(project.row.id, `${day}T00:00:00.000Z`, uniqueKey).first() : null;
  const safeMetadata = sanitizeMetadata(body.metadata);
  await c.env.DB.batch([
    c.env.DB.prepare(`INSERT INTO project_analytics_events
      (id, project_id, event_type, actor_user_hash, session_hash, source_category, geography_code, metadata_json, occurred_at)
      VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)`).bind(crypto.randomUUID(), project.row.id, body.eventType, actorHash, sessionHash, sourceCategory, country, JSON.stringify(safeMetadata), now.toISOString()),
    c.env.DB.prepare(`INSERT INTO project_analytics_daily
      (project_id, day, event_type, total_count, unique_count, returning_count, source_summary_json, geography_summary_json, updated_at)
      VALUES (?1, ?2, ?3, 1, ?4, ?5, ?6, ?7, ?8)
      ON CONFLICT(project_id, day, event_type) DO UPDATE SET total_count = total_count + 1,
        unique_count = unique_count + excluded.unique_count, returning_count = returning_count + excluded.returning_count,
        source_summary_json = json_set(source_summary_json, '$.' || ?9, COALESCE(json_extract(source_summary_json, '$.' || ?9), 0) + 1),
        geography_summary_json = json_set(geography_summary_json, '$.' || ?10, COALESCE(json_extract(geography_summary_json, '$.' || ?10), 0) + 1), updated_at = excluded.updated_at`)
      .bind(project.row.id, day, body.eventType, existing ? 0 : 1, prior ? 1 : 0, JSON.stringify({ [sourceCategory]: 1 }), JSON.stringify({ [country]: 1 }), now.toISOString(), sourceCategory, country),
  ]);
  return c.json({ recorded: true, privacy: "daily rotating hashes; coarse country only" }, 201);
});

marketplaceAnalyticsOperationsRoutes.get("/projects/:id/analytics", loadAuthSession, requireAuth, async (c) => {
  const userId = authenticatedUserId(c); const project = await new ProjectsRepository(c.env.DB).find(c.req.param("id")); if (!project) throw new AppError(404, "PROJECT_NOT_FOUND", "Project not found."); await assertScopedWrite(c.env.DB, userId, project.row);
  const days = Math.min(365, Math.max(7, Number(c.req.query("days") ?? 30) || 30)); const since = new Date(Date.now() - days * 86_400_000).toISOString().slice(0, 10);
  const [series, totals] = await Promise.all([
    c.env.DB.prepare("SELECT day, event_type, total_count, unique_count, returning_count, source_summary_json, geography_summary_json FROM project_analytics_daily WHERE project_id = ?1 AND day >= ?2 ORDER BY day, event_type").bind(project.row.id, since).all<Record<string, unknown>>(),
    c.env.DB.prepare("SELECT event_type, SUM(total_count) AS total, SUM(unique_count) AS unique_count, SUM(returning_count) AS returning_total FROM project_analytics_daily WHERE project_id = ?1 AND day >= ?2 GROUP BY event_type ORDER BY event_type").bind(project.row.id, since).all(),
  ]);
  const map = new Map((totals.results as Array<Record<string, unknown>>).map((row) => [row.event_type, row])); const count = (type: string) => Number(map.get(type)?.total ?? 0);
  return c.json({ sample: false, visibility: "private_creator_analytics", publicCounters: { reproductions: project.item.reproduction_count }, privateMetrics: {
    uniqueViews: Number(map.get("view")?.unique_count ?? 0), returningVisitors: Number(map.get("view")?.returning_total ?? 0), saves: count("save"), forks: count("fork"), buildStarts: count("build_start"), completedBuilds: count("build_complete"), verifiedReproductions: count("verified_reproduction"), bomExports: count("bom_export"), rppsExports: count("rpps_export"), marketplaceReferrals: count("marketplace_referral"), questions: count("question"), missingInformationRequests: count("missing_information_request"), versionAdoption: count("version_adoption"), substitutions: count("substitution"), buildCompletionRate: count("build_start") ? count("build_complete") / count("build_start") : 0,
  }, series: series.results.map(jsonColumns), privacy: "Daily rotating visitor hashes and country-level geography; opted-out users are excluded." });
});

marketplaceAnalyticsOperationsRoutes.post("/marketplace/part-outs", loadAuthSession, requireAuth, async (c) => {
  const userId = authenticatedUserId(c); const body = await parseJson(c, partOutCreateSchema);
  if (body.sourceBuildId) { const build = await new BuildsRepository(c.env.DB).find(body.sourceBuildId); if (!build) throw new AppError(404, "BUILD_NOT_FOUND", "Build not found."); await assertScopedWrite(c.env.DB, userId, build, "build"); }
  if (body.sourceProjectId) { const project = await new ProjectsRepository(c.env.DB).find(body.sourceProjectId); if (!project) throw new AppError(404, "PROJECT_NOT_FOUND", "Project not found."); await assertScopedRead(c.env.DB, userId, project.row); }
  if (body.sourceBomVersionId) { const bom = await c.env.DB.prepare(`SELECT b.owner_user_id, b.organization_id, b.visibility, b.project_id
    FROM bom_versions bv JOIN boms b ON b.id = bv.bom_id WHERE bv.id = ?1`).bind(body.sourceBomVersionId).first<{ owner_user_id: string | null; organization_id: string | null; visibility: "private" | "organization" | "unlisted" | "public"; project_id: string | null }>(); if (!bom) throw new AppError(404, "BOM_VERSION_NOT_FOUND", "BOM version not found."); await assertScopedRead(c.env.DB, userId, bom); if (body.sourceProjectId && bom.project_id && body.sourceProjectId !== bom.project_id) throw new AppError(422, "PART_OUT_SOURCE_MISMATCH", "The selected BOM version does not belong to the selected project."); }
  if (body.sourceListingId) { const listing = await c.env.DB.prepare("SELECT seller_user_id FROM marketplace_listings WHERE id = ?1 AND deleted_at IS NULL").bind(body.sourceListingId).first<{ seller_user_id: string | null }>(); if (!listing || listing.seller_user_id !== userId) throw new AppError(403, "LISTING_ACCESS_DENIED", "You do not own the complete-robot listing."); }
  const id = crypto.randomUUID(); const now = new Date().toISOString(); let items: Array<Record<string, unknown>> = [];
  if (body.sourceBuildId) items = (await c.env.DB.prepare("SELECT id AS source_build_item_id, source_bom_item_id, component_id, description, quantity, status FROM build_items WHERE build_id = ?1 ORDER BY created_at").bind(body.sourceBuildId).all<Record<string, unknown>>()).results;
  else if (body.sourceBomVersionId) items = (await c.env.DB.prepare("SELECT id AS source_bom_item_id, component_id, description, quantity FROM bom_items WHERE bom_version_id = ?1 ORDER BY sort_order").bind(body.sourceBomVersionId).all<Record<string, unknown>>()).results;
  if (!items.length) throw new AppError(422, "PART_OUT_INVENTORY_EMPTY", "The selected build or BOM has no inventory items.");
  const statements: D1PreparedStatement[] = [c.env.DB.prepare(`INSERT INTO marketplace_part_outs
    (id, seller_user_id, source_listing_id, source_project_id, source_build_id, source_bom_version_id, status, currency, created_at, updated_at)
    VALUES (?1, ?2, ?3, ?4, ?5, ?6, 'inventory_review', ?7, ?8, ?8)`).bind(id, userId, body.sourceListingId ?? null, body.sourceProjectId ?? null, body.sourceBuildId ?? null, body.sourceBomVersionId ?? null, body.currency, now)];
  for (const item of items) statements.push(c.env.DB.prepare(`INSERT INTO marketplace_part_out_items
    (id, part_out_id, source_bom_item_id, source_build_item_id, component_id, description, quantity, presence_status, created_at, updated_at)
    VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?9)`).bind(crypto.randomUUID(), id, item.source_bom_item_id ?? null, item.source_build_item_id ?? null, item.component_id ?? null, item.description, item.quantity, item.status === "fabricated" ? "fabricated" : "unconfirmed", now));
  await batch(c.env.DB, statements); return c.json({ id, status: "inventory_review", itemCount: items.length }, 201);
});

marketplaceAnalyticsOperationsRoutes.get("/marketplace/part-outs", loadAuthSession, requireAuth, async (c) => { const rows = await c.env.DB.prepare(`SELECT mpo.*,
  (SELECT COUNT(*) FROM marketplace_part_out_items poi WHERE poi.part_out_id = mpo.id) AS item_count,
  (SELECT COUNT(*) FROM marketplace_part_out_items poi WHERE poi.part_out_id = mpo.id AND poi.presence_status = 'sold') AS sold_count
  FROM marketplace_part_outs mpo WHERE mpo.seller_user_id = ?1 ORDER BY mpo.updated_at DESC LIMIT 200`).bind(authenticatedUserId(c)).all<Record<string, unknown>>(); return c.json({ items: rows.results.map(jsonColumns) }); });

marketplaceAnalyticsOperationsRoutes.get("/marketplace/part-outs/:id", loadAuthSession, requireAuth, async (c) => {
  const partOut = await ownedPartOut(c.env.DB, c.req.param("id"), authenticatedUserId(c)); const [items, bundles, estimates] = await Promise.all([c.env.DB.prepare("SELECT * FROM marketplace_part_out_items WHERE part_out_id = ?1 ORDER BY created_at").bind(partOut.id).all<Record<string, unknown>>(), c.env.DB.prepare("SELECT * FROM marketplace_part_out_bundles WHERE part_out_id = ?1 ORDER BY created_at").bind(partOut.id).all<Record<string, unknown>>(), c.env.DB.prepare("SELECT * FROM marketplace_price_estimates WHERE part_out_id = ?1 ORDER BY created_at DESC").bind(partOut.id).all<Record<string, unknown>>()]); return c.json({ item: jsonColumns(partOut), items: items.results.map(jsonColumns), bundles: bundles.results.map(jsonColumns), estimates: estimates.results.map(jsonColumns) });
});

marketplaceAnalyticsOperationsRoutes.patch("/marketplace/part-outs/:id/items/:itemId", loadAuthSession, requireAuth, async (c) => {
  const partOut = await ownedPartOut(c.env.DB, c.req.param("id"), authenticatedUserId(c)); const body = await parseJson(c, partOutItemSchema); const now = new Date().toISOString();
  const result = await c.env.DB.prepare(`UPDATE marketplace_part_out_items SET presence_status = ?1, condition_grade = ?2,
    test_evidence_json = ?3, pricing_json = ?4, sold_at = CASE WHEN ?1 = 'sold' THEN ?5 ELSE NULL END, updated_at = ?5
    WHERE id = ?6 AND part_out_id = ?7`).bind(body.presenceStatus, body.conditionGrade ?? null, JSON.stringify(body.testEvidence), JSON.stringify(body.pricing), now, c.req.param("itemId"), partOut.id).run(); if (result.meta.changes !== 1) throw new AppError(404, "PART_OUT_ITEM_NOT_FOUND", "Part-out item not found.");
  if (body.presenceStatus === "sold") await c.env.DB.batch([c.env.DB.prepare("UPDATE marketplace_part_outs SET status = 'partial', updated_at = ?1 WHERE id = ?2").bind(now, partOut.id), ...(partOut.source_listing_id ? [c.env.DB.prepare("UPDATE marketplace_listings SET status = 'withdrawn', updated_at = ?1 WHERE id = ?2 AND status IN ('draft','published','reserved')").bind(now, partOut.source_listing_id)] : [])]);
  return c.json({ updated: true, completeRobotListingWithdrawn: body.presenceStatus === "sold" && Boolean(partOut.source_listing_id) });
});

marketplaceAnalyticsOperationsRoutes.post("/marketplace/part-outs/:id/estimates", loadAuthSession, requireAuth, async (c) => {
  const partOut = await ownedPartOut(c.env.DB, c.req.param("id"), authenticatedUserId(c)); const body = await parseJson(c, estimateSchema);
  const items = (await c.env.DB.prepare(`SELECT poi.*, c.category FROM marketplace_part_out_items poi LEFT JOIN components c ON c.id = poi.component_id
    WHERE poi.part_out_id = ?1 AND poi.presence_status NOT IN ('missing','sold','excluded')`).bind(partOut.id).all<Record<string, unknown>>()).results;
  const componentIds = items.map((item) => item.component_id).filter(Boolean); const comparables = componentIds.length ? (await c.env.DB.prepare(`SELECT ml.id, ml.title, ml.price_minor, ml.currency, ml.condition_grade, ml.published_at, mli.component_id
    FROM marketplace_listing_items mli JOIN marketplace_listings ml ON ml.id = mli.listing_id WHERE mli.component_id IN (SELECT value FROM json_each(?1))
    AND ml.price_minor IS NOT NULL AND ml.status IN ('published','reserved','sold','fulfilled') ORDER BY ml.published_at DESC LIMIT 200`).bind(JSON.stringify(componentIds)).all<Record<string, unknown>>()).results : [];
  const knownPrices = comparables.filter((item) => item.currency === partOut.currency).map((item) => Number(item.price_minor)).filter(Number.isFinite).sort((a, b) => a - b);
  const recorded = items.map((item) => { const pricing = parseObject(String(item.pricing_json)); return Number(pricing.expectedMinor ?? pricing.askingMinor ?? 0); }).filter((value) => value > 0);
  const base = recorded.length ? recorded.reduce((sum, value) => sum + value, 0) : knownPrices.length ? median(knownPrices) * items.length : 0;
  if (!base) throw new AppError(422, "PRICE_EVIDENCE_MISSING", "No reliable comparable or seller-entered pricing exists. Add item pricing or comparable records before estimating.");
  const conditionCoverage = items.filter((item) => item.condition_grade).length / items.length; const testCoverage = items.filter((item) => parseArray(String(item.test_evidence_json)).length).length / items.length; const completeness = items.filter((item) => item.presence_status === "present").length / items.length; const confidence = Math.min(0.9, 0.25 + Math.min(0.3, knownPrices.length * 0.03) + conditionCoverage * 0.15 + testCoverage * 0.15 + completeness * 0.05);
  const partOutExpected = Math.round(base); const completeExpected = Math.round(base * Math.max(0.6, 0.85 - (1 - completeness) * 0.3)); const estimates = [{ type: "part_out_total", expected: partOutExpected }, { type: "complete_robot", expected: completeExpected }]; const now = new Date().toISOString();
  const comparableRecords = comparables.map((item) => ({ listingId: item.id, title: item.title, priceMinor: item.price_minor, currency: item.currency, condition: item.condition_grade, observedAt: item.published_at }));
  const statements = estimates.map((estimate) => c.env.DB.prepare(`INSERT INTO marketplace_price_estimates
    (id, part_out_id, estimate_type, currency, low_minor, expected_minor, high_minor, assumptions_json, comparable_records_json, source_freshness_at, confidence, disclaimer, created_at)
    VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13)`)
    .bind(crypto.randomUUID(), partOut.id, estimate.type, partOut.currency, Math.round(estimate.expected * 0.7), estimate.expected, Math.round(estimate.expected * 1.3), JSON.stringify({ ageYears: body.ageAssumptionYears, completeness, conditionCoverage, testCoverage, estimatedFeesMinor: Math.round(estimate.expected * body.estimatedFeeRate), feeRate: body.estimatedFeeRate, shippingComplexity: body.shippingComplexity, notes: body.notes }), JSON.stringify(comparableRecords), comparables[0]?.published_at ?? null, confidence, "Estimate only—not a guaranteed sale value. Actual fees, shipping, demand, condition, and completeness may change proceeds.", now));
  await c.env.DB.batch([...statements, c.env.DB.prepare("UPDATE marketplace_part_outs SET status = 'priced', part_out_estimate_json = ?1, complete_robot_estimate_json = ?2, updated_at = ?3 WHERE id = ?4").bind(JSON.stringify({ expectedMinor: partOutExpected, confidence }), JSON.stringify({ expectedMinor: completeExpected, confidence }), now, partOut.id)]);
  return c.json({ estimates: estimates.map((item) => ({ estimateType: item.type, currency: partOut.currency, lowMinor: Math.round(item.expected * 0.7), expectedMinor: item.expected, highMinor: Math.round(item.expected * 1.3), comparableRecords, assumptions: { completeness, conditionCoverage, testCoverage, estimatedFeeRate: body.estimatedFeeRate, shippingComplexity: body.shippingComplexity, ageYears: body.ageAssumptionYears }, confidence, sourceFreshnessAt: comparables[0]?.published_at ?? null, disclaimer: "Estimate only—not a guaranteed sale value." })) });
});

marketplaceAnalyticsOperationsRoutes.post("/marketplace/part-outs/:id/bundles", loadAuthSession, requireAuth, async (c) => { const userId = authenticatedUserId(c); const partOut = await ownedPartOut(c.env.DB, c.req.param("id"), userId); const body = await parseJson(c, bundleSchema); const valid = await c.env.DB.prepare("SELECT COUNT(*) AS value FROM marketplace_part_out_items WHERE part_out_id = ?1 AND id IN (SELECT value FROM json_each(?2)) AND presence_status NOT IN ('sold','missing','excluded')").bind(partOut.id, JSON.stringify(Array.from(new Set(body.itemIds)))).first<{ value: number }>(); if (Number(valid?.value ?? 0) !== new Set(body.itemIds).size) throw new AppError(422, "BUNDLE_ITEMS_INVALID", "Every bundled item must be available in this part-out."); const id = crypto.randomUUID(); const now = new Date().toISOString(); const statements: D1PreparedStatement[] = [c.env.DB.prepare("INSERT INTO marketplace_part_out_bundles (id, part_out_id, name, rationale, pricing_json, created_at, updated_at) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?6)").bind(id, partOut.id, body.name, body.rationale ?? null, JSON.stringify(body.pricing), now), ...Array.from(new Set(body.itemIds)).map((itemId) => c.env.DB.prepare("INSERT INTO marketplace_part_out_bundle_items (bundle_id, part_out_item_id, quantity) VALUES (?1, ?2, 1)").bind(id, itemId))]; await c.env.DB.batch(statements); return c.json({ id }, 201); });

marketplaceAnalyticsOperationsRoutes.post("/marketplace/part-outs/:id/draft-listings", loadAuthSession, requireAuth, async (c) => {
  const userId = authenticatedUserId(c); const partOut = await ownedPartOut(c.env.DB, c.req.param("id"), userId); const body = await parseJson(c, draftListingsSchema); const itemIds = Array.from(new Set(body.itemIds)); const bundleIds = Array.from(new Set(body.bundleIds));
  const [items, bundles] = await Promise.all([
    itemIds.length ? c.env.DB.prepare(`SELECT poi.*, c.category FROM marketplace_part_out_items poi LEFT JOIN components c ON c.id = poi.component_id
      WHERE poi.part_out_id = ?1 AND poi.id IN (SELECT value FROM json_each(?2)) AND poi.presence_status NOT IN ('sold','missing','excluded') AND poi.draft_listing_id IS NULL`).bind(partOut.id, JSON.stringify(itemIds)).all<Record<string, unknown>>() : Promise.resolve({ results: [] as Array<Record<string, unknown>> }),
    bundleIds.length ? c.env.DB.prepare(`SELECT pob.*, group_concat(poi.description, ', ') AS item_descriptions, SUM(pobi.quantity) AS quantity
      FROM marketplace_part_out_bundles pob JOIN marketplace_part_out_bundle_items pobi ON pobi.bundle_id = pob.id JOIN marketplace_part_out_items poi ON poi.id = pobi.part_out_item_id
      WHERE pob.part_out_id = ?1 AND pob.id IN (SELECT value FROM json_each(?2)) AND pob.draft_listing_id IS NULL
      GROUP BY pob.id`).bind(partOut.id, JSON.stringify(bundleIds)).all<Record<string, unknown>>() : Promise.resolve({ results: [] as Array<Record<string, unknown>> }),
  ]);
  if (items.results.length !== itemIds.length || bundles.results.length !== bundleIds.length) throw new AppError(422, "DRAFT_LISTING_SELECTION_INVALID", "Selections must be available, unsold, and without an existing draft listing.");
  const now = new Date().toISOString(); const created: Array<{ sourceType: "item" | "bundle"; sourceId: string; listingId: string }> = []; const statements: D1PreparedStatement[] = [];
  for (const source of [...items.results.map((item) => ({ type: "item" as const, row: item })), ...bundles.results.map((bundle) => ({ type: "bundle" as const, row: bundle }))]) {
    const listingId = crypto.randomUUID(); const sourceId = String(source.row.id); const title = source.type === "item" ? String(source.row.description) : String(source.row.name); const pricing = parseObject(String(source.row.pricing_json)); const priceMinor = Number(pricing.askingMinor ?? pricing.expectedMinor ?? 0); const condition = source.type === "item" && ["A", "B", "C", "untested", "for_parts", "not_applicable"].includes(String(source.row.condition_grade)) ? String(source.row.condition_grade) : "untested"; const description = source.type === "item" ? `Part-out inventory item: ${title}. Presence: ${String(source.row.presence_status).replaceAll("_", " ")}. Confirm details before publishing.` : `Part-out bundle containing ${String(source.row.item_descriptions)}. ${String(source.row.rationale ?? "Confirm bundle details before publishing.")}`; const slug = `${slugify(title)}-${listingId.slice(0, 8)}`;
    statements.push(c.env.DB.prepare(`INSERT INTO marketplace_listings
      (id, slug, seller_user_id, listing_type, title, description, category, condition_grade, currency, price_minor, quantity, status, visibility, source_build_id, source_component_id, version, is_demo, created_at, updated_at)
      VALUES (?1, ?2, ?3, 'sell', ?4, ?5, ?6, ?7, ?8, ?9, ?10, 'draft', 'private', ?11, ?12, 1, 0, ?13, ?13)`).bind(listingId, slug, userId, title.slice(0, 160), description, source.type === "item" ? String(source.row.category ?? "robot-component") : "robot-bundle", condition, partOut.currency, priceMinor > 0 ? Math.round(priceMinor) : null, Number(source.row.quantity ?? 1), partOut.source_build_id ?? null, source.type === "item" ? source.row.component_id ?? null : null, now));
    statements.push(c.env.DB.prepare("INSERT INTO marketplace_listing_details (listing_id, provenance_text, updated_at) VALUES (?1, ?2, ?3)").bind(listingId, `Generated as an editable draft from part-out workflow ${partOut.id}.`, now));
    if (source.type === "item") { statements.push(c.env.DB.prepare("INSERT INTO marketplace_listing_items (id, listing_id, component_id, description, quantity) VALUES (?1, ?2, ?3, ?4, ?5)").bind(crypto.randomUUID(), listingId, source.row.component_id ?? null, title, Number(source.row.quantity ?? 1))); statements.push(c.env.DB.prepare("UPDATE marketplace_part_out_items SET draft_listing_id = ?1, updated_at = ?2 WHERE id = ?3 AND part_out_id = ?4").bind(listingId, now, sourceId, partOut.id)); }
    else { statements.push(c.env.DB.prepare("INSERT INTO marketplace_listing_items (id, listing_id, description, quantity) VALUES (?1, ?2, ?3, ?4)").bind(crypto.randomUUID(), listingId, title, Number(source.row.quantity ?? 1))); statements.push(c.env.DB.prepare("UPDATE marketplace_part_out_bundles SET draft_listing_id = ?1, updated_at = ?2 WHERE id = ?3 AND part_out_id = ?4").bind(listingId, now, sourceId, partOut.id)); }
    created.push({ sourceType: source.type, sourceId, listingId });
  }
  await batch(c.env.DB, statements); return c.json({ items: created, status: "draft", requiresReviewBeforePublication: true }, 201);
});

marketplaceAnalyticsOperationsRoutes.post("/operations/appeals", loadAuthSession, requireAuth, async (c) => { const userId = authenticatedUserId(c); const body = await parseJson(c, z.object({ sourceEntityType: z.string().trim().min(1).max(100), sourceEntityId: z.string().trim().min(1).max(200), title: z.string().trim().min(4).max(300), summary: z.string().trim().min(4).max(4_000) }).strict()); const id = crypto.randomUUID(); const now = new Date().toISOString(); await c.env.DB.prepare(`INSERT INTO operations_cases (id, case_type, source_entity_type, source_entity_id, title, summary, priority, status, opened_by_user_id, created_at, updated_at) VALUES (?1, 'appeal', ?2, ?3, ?4, ?5, 'medium', 'appealed', ?6, ?7, ?7)`).bind(id, body.sourceEntityType, body.sourceEntityId, body.title, body.summary, userId, now).run(); return c.json({ id, status: "appealed" }, 201); });

marketplaceAnalyticsOperationsRoutes.use("/admin/operations", loadAuthSession, requireAuth, requirePlatformRole("moderator", "administrator"));
marketplaceAnalyticsOperationsRoutes.use("/admin/operations/*", loadAuthSession, requireAuth, requirePlatformRole("moderator", "administrator"));
marketplaceAnalyticsOperationsRoutes.get("/admin/operations/overview", async (c) => {
  const results = await c.env.DB.batch([
    c.env.DB.prepare("SELECT COUNT(*) AS value FROM import_jobs WHERE status IN ('accepted','processing','partial','failed')"),
    c.env.DB.prepare("SELECT COUNT(*) AS value FROM bom_verifications WHERE status IN ('submitted','under_review','disputed')"),
    c.env.DB.prepare("SELECT COUNT(*) AS value FROM operations_cases WHERE status NOT IN ('resolved','dismissed')"),
    c.env.DB.prepare("SELECT COUNT(*) AS value FROM ai_friction_events WHERE resolution_status IN ('open','triaged','assigned') AND deleted_at IS NULL"),
    c.env.DB.prepare("SELECT COUNT(*) AS value FROM messaging_reports WHERE status IN ('open','reviewing','appealed')"),
    c.env.DB.prepare("SELECT COALESCE(SUM(estimated_cost_microunits),0) AS value FROM ai_task_runs WHERE created_at >= datetime('now','-30 days')"),
    c.env.DB.prepare("SELECT COUNT(*) AS value FROM import_sources WHERE status = 'active'"),
    c.env.DB.prepare("SELECT COUNT(*) AS value FROM ai_evaluation_runs WHERE status IN ('queued','running','failed')"),
    c.env.DB.prepare("SELECT COUNT(*) AS value FROM forum_reports WHERE status IN ('open','reviewing')"),
    c.env.DB.prepare("SELECT COUNT(*) AS value FROM marketplace_reports WHERE status IN ('open','reviewing')"),
  ]); const value = (index: number) => Number((results[index].results[0] as { value?: number } | undefined)?.value ?? 0);
  return c.json({ importJobs: value(0), bomVerification: value(1), openCases: value(2), aiFriction: value(3), messagingReports: value(4), aiCostMicrounits30d: value(5), activeDataSources: value(6), aiEvaluationsRequiringAttention: value(7), communityReports: value(8), marketplaceReports: value(9), sample: false });
});
marketplaceAnalyticsOperationsRoutes.get("/admin/operations/queues", async (c) => { const [imports, boms, reports, communityReports, marketplaceReports, friction, sources, evaluations, costs] = await Promise.all([
  c.env.DB.prepare("SELECT * FROM import_jobs ORDER BY created_at DESC LIMIT 200").all<Record<string, unknown>>(), c.env.DB.prepare("SELECT * FROM bom_verifications ORDER BY created_at DESC LIMIT 200").all<Record<string, unknown>>(), c.env.DB.prepare("SELECT * FROM messaging_reports ORDER BY created_at DESC LIMIT 200").all<Record<string, unknown>>(), c.env.DB.prepare("SELECT * FROM forum_reports ORDER BY created_at DESC LIMIT 200").all<Record<string, unknown>>(), c.env.DB.prepare("SELECT * FROM marketplace_reports ORDER BY created_at DESC LIMIT 200").all<Record<string, unknown>>(), c.env.DB.prepare("SELECT * FROM ai_friction_events WHERE deleted_at IS NULL ORDER BY created_at DESC LIMIT 300").all<Record<string, unknown>>(), c.env.DB.prepare("SELECT * FROM import_sources ORDER BY priority, name").all<Record<string, unknown>>(), c.env.DB.prepare("SELECT * FROM ai_evaluation_runs ORDER BY created_at DESC LIMIT 200").all<Record<string, unknown>>(), c.env.DB.prepare("SELECT task_type, provider_key, model_key, COUNT(*) AS runs, SUM(estimated_cost_microunits) AS cost_microunits, AVG(latency_ms) AS average_latency_ms FROM ai_task_runs WHERE created_at >= datetime('now','-30 days') GROUP BY task_type, provider_key, model_key ORDER BY cost_microunits DESC").all<Record<string, unknown>>()]); return c.json({ imports: imports.results.map(jsonColumns), bomVerifications: boms.results.map(jsonColumns), messagingReports: reports.results, communityReports: communityReports.results.map(jsonColumns), marketplaceReports: marketplaceReports.results, aiFriction: friction.results.map(jsonColumns), dataSources: sources.results.map(jsonColumns), evaluations: evaluations.results.map(jsonColumns), aiCost: costs.results }); });
marketplaceAnalyticsOperationsRoutes.get("/admin/operations/cases", async (c) => { const status = c.req.query("status")?.slice(0, 30) ?? ""; const rows = await c.env.DB.prepare("SELECT * FROM operations_cases WHERE (?1 = '' OR status = ?1) ORDER BY CASE priority WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END, created_at DESC LIMIT 500").bind(status).all<Record<string, unknown>>(); return c.json({ items: rows.results }); });
marketplaceAnalyticsOperationsRoutes.post("/admin/operations/cases", async (c) => { const userId = authenticatedUserId(c); const body = await parseJson(c, operationsCaseSchema); const id = crypto.randomUUID(); const now = new Date().toISOString(); await c.env.DB.prepare(`INSERT INTO operations_cases
  (id, case_type, source_entity_type, source_entity_id, title, summary, priority, status, opened_by_user_id, created_at, updated_at)
  VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, 'open', ?8, ?9, ?9)`).bind(id, body.caseType, body.sourceEntityType ?? null, body.sourceEntityId ?? null, body.title, body.summary ?? null, body.priority, userId, now).run(); return c.json({ id }, 201); });
marketplaceAnalyticsOperationsRoutes.patch("/admin/operations/cases/:id", async (c) => { const userId = authenticatedUserId(c); const body = await parseJson(c, operationsUpdateSchema); const now = new Date().toISOString(); const result = await c.env.DB.prepare(`UPDATE operations_cases SET status = ?1, priority = COALESCE(?2, priority), assigned_to_user_id = ?3, resolution = ?4,
  resolved_at = CASE WHEN ?1 IN ('resolved','dismissed') THEN ?5 ELSE NULL END, updated_at = ?5 WHERE id = ?6`).bind(body.status, body.priority ?? null, body.assignedToUserId ?? null, body.resolution ?? null, now, c.req.param("id")).run(); if (result.meta.changes !== 1) throw new AppError(404, "OPERATIONS_CASE_NOT_FOUND", "Operations case not found."); await c.env.DB.prepare("INSERT INTO operations_case_events (id, case_id, actor_user_id, event_type, detail_json, created_at) VALUES (?1, ?2, ?3, 'case.updated', ?4, ?5)").bind(crypto.randomUUID(), c.req.param("id"), userId, JSON.stringify(body), now).run(); await recordAuditEvent(c.env.DB, { actorUserId: userId, action: "operations.case.update", entityType: "operations_case", entityId: c.req.param("id"), requestId: c.get("requestId"), after: body }); return c.json({ updated: true }); });
marketplaceAnalyticsOperationsRoutes.post("/admin/operations/friction-clusters", async (c) => { const userId = authenticatedUserId(c); const body = await parseJson(c, frictionClusterSchema); const id = crypto.randomUUID(); const now = new Date().toISOString(); const statements: D1PreparedStatement[] = [c.env.DB.prepare(`INSERT INTO ai_friction_clusters
  (id, title, description, feature, priority, status, assigned_to_user_id, created_by_user_id, created_at, updated_at) VALUES (?1, ?2, ?3, ?4, ?5, 'open', ?6, ?7, ?8, ?8)`).bind(id, body.title, body.description ?? null, body.feature ?? null, body.priority, body.assignedToUserId ?? null, userId, now), ...body.eventIds.map((eventId) => c.env.DB.prepare("INSERT OR IGNORE INTO ai_friction_cluster_members (cluster_id, friction_event_id, created_at) VALUES (?1, ?2, ?3)").bind(id, eventId, now))]; await batch(c.env.DB, statements); return c.json({ id, eventCount: body.eventIds.length }, 201); });

async function ownedPartOut(db: D1Database, id: string, userId: string): Promise<Record<string, unknown> & { id: string; currency: string; source_listing_id: string | null }> { const row = await db.prepare("SELECT * FROM marketplace_part_outs WHERE id = ?1 AND seller_user_id = ?2").bind(id, userId).first<Record<string, unknown> & { id: string; currency: string; source_listing_id: string | null }>(); if (!row) throw new AppError(404, "PART_OUT_NOT_FOUND", "Part-out workflow not found."); return row; }
function slugify(value: string): string { return value.normalize("NFKD").toLowerCase().replace(/[^a-z0-9]+/gu, "-").replace(/^-+|-+$/gu, "").slice(0, 80) || "part-out"; }
function categorizeReferrer(value: string | undefined): string { if (!value) return "direct"; try { const host = new URL(value).hostname.toLowerCase(); if (host.endsWith("robopartpicker.com") || host === "localhost") return "internal"; if (/google|bing|duckduckgo|yahoo/u.test(host)) return "search"; if (/reddit|youtube|linkedin|facebook|x\.com|twitter/u.test(host)) return "social"; return "external"; } catch { return "unknown"; } }
function countryCode(request: Request): string { const country = (request as Request & { cf?: { country?: string } }).cf?.country?.toUpperCase(); return country && /^[A-Z]{2}$/u.test(country) ? country : "ZZ"; }
function sanitizeMetadata(value: Record<string, unknown>): Record<string, unknown> { return Object.fromEntries(Object.entries(value).filter(([key]) => !/(email|name|address|ip|token|secret|credential|url)/iu.test(key)).slice(0, 20).map(([key, item]) => [key, typeof item === "string" ? item.slice(0, 200) : typeof item === "number" || typeof item === "boolean" ? item : "[structured]" ])); }
async function hash(value: string): Promise<string> { return [...new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)))].map((byte) => byte.toString(16).padStart(2, "0")).join(""); }
function jsonColumns(row: Record<string, unknown>) { const output = { ...row }; for (const [key, value] of Object.entries(row)) if (key.endsWith("_json") && typeof value === "string") { try { output[key.replace(/_json$/u, "")] = JSON.parse(value); } catch { output[key.replace(/_json$/u, "")] = null; } delete output[key]; } return output; }
function parseObject(value: string): Record<string, unknown> { try { const parsed = JSON.parse(value); return parsed && typeof parsed === "object" && !Array.isArray(parsed) ? parsed : {}; } catch { return {}; } }
function parseArray(value: string): unknown[] { try { const parsed = JSON.parse(value); return Array.isArray(parsed) ? parsed : []; } catch { return []; } }
function median(values: number[]): number { const middle = Math.floor(values.length / 2); return values.length % 2 ? values[middle] : Math.round((values[middle - 1] + values[middle]) / 2); }
async function batch(db: D1Database, statements: D1PreparedStatement[]) { for (let offset = 0; offset < statements.length; offset += 80) await db.batch(statements.slice(offset, offset + 80)); }
