import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, FileCheck2, Loader2, Send } from "lucide-react";
import { RichTechnicalEditor } from "@/components/common/RichTechnicalEditor";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "@/hooks/use-toast";
import { bomVerificationApi } from "@/lib/api/systems";

export default function BomVerification() { const { id = "" } = useParams<{ id: string }>(); const { user, loading } = useAuth(); const client = useQueryClient(); const [editing, setEditing] = useState(false); const [json, setJson] = useState(""); const [description, setDescription] = useState(""); const [reviewNotes, setReviewNotes] = useState(""); const [busy, setBusy] = useState(false); const detail = useQuery({ queryKey: ["bom-verification", id], queryFn: ({ signal }) => bomVerificationApi.get(id, signal), enabled: Boolean(id && user), retry: false }); const currentLines = useMemo(() => detail.data?.lines.filter((line) => line.version_id === detail.data?.item.current_version_id) ?? [], [detail.data]);
  useEffect(() => { if (!editing) setJson(JSON.stringify(currentLines.map((line) => ({ lineKey: line.line_key, rawText: line.raw_text, componentId: line.component_id, identity: line.identity ?? {}, quantity: line.quantity, status: line.status, confidence: line.confidence, notes: line.notes })), null, 2)); }, [currentLines, editing]);
  const refresh = () => client.invalidateQueries({ queryKey: ["bom-verification", id] }); const correct = async () => { setBusy(true); try { const lines = JSON.parse(json) as Array<Record<string, unknown>>; await bomVerificationApi.correct(id, detail.data?.versions.find((version) => version.id === detail.data?.item.current_version_id)?.snapshot ?? {}, lines, description); setEditing(false); await refresh(); toast({ title: "Corrected BOM version saved", description: "The original version remains preserved." }); } catch (error) { toast({ title: "Correction failed", description: message(error), variant: "destructive" }); } finally { setBusy(false); } }; const submit = async () => { setBusy(true); try { await bomVerificationApi.submit(id); await refresh(); } catch (error) { toast({ title: "Submission failed", description: message(error), variant: "destructive" }); } finally { setBusy(false); } }; const review = async (decision: "request_changes" | "verify" | "dispute" | "reject") => { setBusy(true); try { await bomVerificationApi.review(id, decision, reviewNotes || `Reviewer decision: ${decision.replaceAll("_", " ")}`); await refresh(); toast({ title: "Review recorded" }); } catch (error) { toast({ title: "Review failed", description: message(error), variant: "destructive" }); } finally { setBusy(false); } };
  if (loading || detail.isLoading) return <State><Loader2 className="h-5 w-5 animate-spin" /> Loading verification…</State>; if (!user) return <State><FileCheck2 className="h-7 w-7 text-primary" /><Link to={`/auth?next=${encodeURIComponent(`/bom-verifications/${id}`)}`} className="btn-primary">Sign in</Link></State>; if (detail.error || !detail.data) return <State>{message(detail.error)}</State>; const item = detail.data.item;
  return <main className="mx-auto max-w-6xl px-4 py-6"><div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><div className="section-title">BOM verification workflow</div><h1 className="text-[22px] font-bold">Verification {item.id.slice(0, 8)}</h1><div className="mt-2 flex gap-2"><span className="badge-neutral">{item.status.replaceAll("_", " ")}</span><span className="badge-neutral">{item.source_type.replaceAll("_", " ")}</span></div></div><div className="flex flex-wrap gap-2">{["draft", "ai_extracted", "user_confirmed"].includes(item.status) && <button disabled={busy} onClick={() => void submit()} className="btn-primary min-h-10"><Send className="h-4 w-4" /> Submit for review</button>}<button onClick={() => setEditing((value) => !value)} className="btn-ghost min-h-10">{editing ? "Cancel correction" : "Create corrected version"}</button></div></div>
    <div className="mb-4 rounded border border-caution/40 bg-caution/5 p-3 text-xs"><strong>No reliable BOM lines are invented.</strong> Unresolved identities remain visible until the submitter corrects them or a maintainer verifies evidence. Original and corrected versions are immutable.</div>
    {editing && <section className="surface-card mb-4 p-4"><h2 className="text-sm font-semibold">Corrected version</h2><p className="mt-1 text-[11px] text-muted-foreground">Edit the structured line array. Each line requires lineKey, rawText, identity, status, and confidence.</p><textarea aria-label="Corrected BOM lines JSON" value={json} onChange={(event) => setJson(event.target.value)} rows={18} className="mt-3 w-full resize-y rounded border border-input bg-background p-3 font-mono text-xs" /><label className="mt-3 block text-xs">Change description<input value={description} onChange={(event) => setDescription(event.target.value)} className="input-bare mt-1 min-h-11 w-full" /></label><button disabled={busy || description.trim().length < 2} onClick={() => void correct()} className="btn-primary mt-3 min-h-11 disabled:opacity-50">Save corrected version</button></section>}
    <section className="surface-card overflow-hidden"><div className="flex items-center justify-between border-b border-border p-3"><span className="section-title">Current version lines</span><span className="badge-neutral">{currentLines.filter((line) => line.status === "unresolved").length} unresolved</span></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-muted/50 text-[10px] uppercase text-muted-foreground"><tr><th className="p-3">Line</th><th className="p-3">Quantity</th><th className="p-3">Identity</th><th className="p-3">Status</th><th className="p-3">Confidence</th></tr></thead><tbody>{currentLines.map((line) => <tr key={line.id} className="border-t border-border"><td className="p-3"><div className="font-medium">{line.raw_text}</div><div className="mono text-[10px] text-muted-foreground">{line.line_key}</div></td><td className="p-3">{line.quantity ?? "—"}</td><td className="p-3"><pre className="max-w-sm overflow-auto text-[10px]">{JSON.stringify(line.identity)}</pre></td><td className="p-3"><span className={line.status === "resolved" ? "pill pill-good" : line.status === "unresolved" ? "pill pill-warn" : "badge-neutral"}>{line.status}</span></td><td className="p-3 mono">{Math.round(Number(line.confidence) * 100)}%</td></tr>)}</tbody></table></div></section>
    <section className="mt-4 grid gap-4 lg:grid-cols-2"><div className="surface-card p-4"><div className="section-title mb-2">Version history</div>{detail.data.versions.map((version) => <div key={version.id} className="border-b border-border py-2 text-xs last:border-0"><div className="font-medium">Version {version.version_number}</div><p className="text-muted-foreground">{version.change_description}</p><time className="text-[10px] text-muted-foreground">{new Date(version.created_at).toLocaleString()}</time></div>)}</div><div className="surface-card p-4"><div className="section-title mb-2">Maintainer review</div><RichTechnicalEditor value={reviewNotes} onChange={setReviewNotes} label="Review notes" maxLength={4_000} minRows={4} /><div className="mt-3 flex flex-wrap gap-2"><button disabled={busy} onClick={() => void review("verify")} className="btn-primary min-h-10"><CheckCircle2 className="h-4 w-4" /> Verify</button><button disabled={busy} onClick={() => void review("request_changes")} className="btn-ghost min-h-10">Request changes</button><button disabled={busy} onClick={() => void review("dispute")} className="btn-ghost min-h-10">Dispute</button><button disabled={busy} onClick={() => void review("reject")} className="btn-ghost min-h-10 text-negative">Reject</button></div><div className="mt-4 space-y-2">{detail.data.reviews.map((review) => <div key={review.id} className="rounded border border-border p-2 text-[11px]"><strong>{review.decision.replaceAll("_", " ")}</strong><p>{review.notes}</p></div>)}</div></div></section>
  </main>; }
function State({ children }: { children: React.ReactNode }) { return <main className="mx-auto flex min-h-[50vh] max-w-2xl flex-col items-center justify-center gap-3 px-4 text-center">{children}</main>; }
function message(error: unknown): string { return error instanceof Error ? error.message : "Unexpected error."; }
