import { useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, ArrowLeft, Boxes, FileUp, Loader2, RefreshCw, StopCircle } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "@/hooks/use-toast";
import { ApiError } from "@/lib/api/client";
import { uploadFile, type FileKind } from "@/lib/api/files";
import { importJobsApi } from "@/lib/api/systems";
import { DataReviewPanel } from "@/components/admin/data-review/DataReviewPanel";

export default function ImportJobs() {
  const { jobId } = useParams<{ jobId: string }>();
  const { user, loading } = useAuth();
  if (loading) return <State><Loader2 className="h-5 w-5 animate-spin" /> Loading account…</State>;
  if (!user) return <State><FileUp className="h-7 w-7 text-primary" /><h1 className="text-xl font-bold">Sign in to import project files</h1><Link to={`/auth?next=${encodeURIComponent(jobId ? `/imports/${jobId}` : "/imports")}`} className="btn-primary">Sign in</Link></State>;
  return jobId ? <ImportJobDetail jobId={jobId} /> : <ImportJobList />;
}

function ImportJobList() {
  const navigate = useNavigate(); const client = useQueryClient(); const [files, setFiles] = useState<File[]>([]); const [busy, setBusy] = useState(false);
  const jobs = useQuery({ queryKey: ["project-import-jobs"], queryFn: ({ signal }) => importJobsApi.list(signal), refetchInterval: (query) => query.state.data?.items.some((item) => ["accepted", "processing"].includes(item.status)) ? 2_000 : false });
  const queue = async () => { if (!files.length) return; setBusy(true); try { const uploaded: string[] = []; for (const file of files) { const result = await uploadFile(file, kindFor(file.name)); if (result.status !== "ready") throw new Error(`${file.name} did not pass upload validation.`); uploaded.push(result.fileId); } const created = await importJobsApi.create(uploaded); await client.invalidateQueries({ queryKey: ["project-import-jobs"] }); navigate(`/imports/${created.item.id}`); } catch (error) { toast({ title: "Import could not be queued", description: message(error), variant: "destructive" }); } finally { setBusy(false); } };
  return <main className="mx-auto max-w-6xl px-4 py-6">
    <div className="mb-4"><div className="section-title">Project ingestion</div><h1 className="text-[22px] font-bold">Import and analysis jobs</h1><p className="mt-1 max-w-3xl text-xs text-muted-foreground">Upload robot descriptions, CAD, BOMs, ROS files, archives, documents, or repositories exported as archives. Untrusted scripts and Xacro are inspected as data and never executed in the Worker.</p></div>
    <section className="surface-card mb-5 p-4"><div className="grid gap-3 md:grid-cols-[minmax(0,1fr)_auto] md:items-end"><label className="block"><span className="mb-1 block text-xs font-medium">Files</span><input type="file" multiple disabled={busy} onChange={(event) => setFiles(Array.from(event.target.files ?? []))} className="block min-h-11 w-full rounded border border-input bg-background p-2 text-xs" /><span className="mt-1 block text-[10px] text-muted-foreground">Large/native formats run asynchronously in an isolated processing container. Archives are inventoried without executing their contents.</span></label><button disabled={busy || files.length === 0} onClick={() => void queue()} className="btn-primary min-h-11 disabled:opacity-50">{busy ? <><Loader2 className="h-4 w-4 animate-spin" /> Uploading…</> : <><FileUp className="h-4 w-4" /> Queue {files.length || ""} file{files.length === 1 ? "" : "s"}</>}</button></div></section>
    <section className="surface-card overflow-hidden"><div className="border-b border-border p-3 section-title">Your jobs</div>{jobs.isLoading && <div className="p-5 text-sm text-muted-foreground">Loading imports…</div>}{jobs.error && <div className="p-5 text-sm text-negative">{message(jobs.error)}</div>}{jobs.data?.items.length === 0 && <div className="p-8 text-center text-sm text-muted-foreground">No import jobs yet.</div>}<div className="divide-y divide-border">{jobs.data?.items.map((job) => <Link key={job.id} to={`/imports/${job.id}`} className="grid gap-2 p-3 hover:bg-muted/50 sm:grid-cols-[minmax(0,1fr)_120px_180px] sm:items-center"><div className="min-w-0"><div className="mono truncate text-xs">{job.id}</div><div className="mt-1 text-[11px] text-muted-foreground">{job.current_stage ?? "queued"} · {job.processor_kind ?? "automatic"} processor</div></div><Status value={job.status} /><div><div className="h-2 overflow-hidden rounded bg-muted"><div className="h-full bg-primary" style={{ width: `${job.progress_percent ?? 0}%` }} /></div><div className="mt-1 text-right mono text-[10px]">{job.progress_percent ?? 0}%</div></div></Link>)}</div></section>
    <DataReviewPanel />
  </main>;
}

function ImportJobDetail({ jobId }: { jobId: string }) {
  const client = useQueryClient(); const [busy, setBusy] = useState(false);
  const job = useQuery({ queryKey: ["project-import-job", jobId], queryFn: ({ signal }) => importJobsApi.get(jobId, signal), refetchInterval: (query) => ["accepted", "processing"].includes(query.state.data?.item.status ?? "") ? 1_500 : false });
  const structure = useQuery({ queryKey: ["robot-structure", jobId], queryFn: ({ signal }) => importJobsApi.structure(jobId, signal), enabled: Boolean(job.data && ["complete", "partial"].includes(job.data.item.status)), retry: false });
  const act = async (kind: "cancel" | "retry") => { setBusy(true); try { await importJobsApi[kind](jobId); await client.invalidateQueries({ queryKey: ["project-import-job", jobId] }); toast({ title: kind === "cancel" ? "Cancellation requested" : "Import queued again" }); } catch (error) { toast({ title: `Could not ${kind} import`, description: message(error), variant: "destructive" }); } finally { setBusy(false); } };
  if (job.isLoading) return <State><Loader2 className="h-5 w-5 animate-spin" /> Loading import…</State>;
  if (job.error || !job.data) return <State><AlertTriangle className="h-6 w-6 text-negative" />{message(job.error)}</State>;
  const item = job.data.item; const running = ["accepted", "processing"].includes(item.status); const retryable = ["failed", "partial", "cancelled"].includes(item.status);
  return <main className="mx-auto max-w-6xl px-4 py-5">
    <Link to="/imports" className="mb-3 inline-flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground"><ArrowLeft className="h-3.5 w-3.5" /> All imports</Link>
    <div className="mb-4 flex flex-wrap items-start justify-between gap-3"><div><div className="section-title">Import job</div><h1 className="mono break-all text-lg font-bold">{item.id}</h1><div className="mt-2 flex flex-wrap items-center gap-2"><Status value={item.status} /><span className="text-xs text-muted-foreground">{item.current_stage ?? "queued"} · {item.processor_kind ?? "automatic"}</span></div></div><div className="flex gap-2">{running && <button disabled={busy} onClick={() => void act("cancel")} className="btn-ghost btn-sm min-h-10"><StopCircle className="h-4 w-4" /> Cancel</button>}{retryable && <button disabled={busy} onClick={() => void act("retry")} className="btn-primary btn-sm min-h-10"><RefreshCw className="h-4 w-4" /> Retry</button>}</div></div>
    <div className="mb-5 surface-card p-4"><div className="mb-2 flex justify-between text-xs"><span>{item.current_stage ?? "Queued"}</span><span className="mono">{item.progress_percent ?? 0}%</span></div><div className="h-3 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary transition-all" style={{ width: `${item.progress_percent ?? 0}%` }} /></div>{item.last_error && <p className="mt-3 rounded border border-negative/30 bg-negative/5 p-2 text-xs text-negative">{item.last_error}</p>}</div>
    <section className="surface-card mb-5 overflow-hidden"><div className="border-b border-border p-3 section-title">Per-file results and provenance</div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-muted/50 text-[10px] uppercase text-muted-foreground"><tr><th className="p-3">Source file</th><th className="p-3">Format</th><th className="p-3">Processor</th><th className="p-3">Status</th><th className="p-3">Warnings / missing dependencies</th></tr></thead><tbody>{job.data.files.map((file) => <tr key={file.id} className="border-t border-border align-top"><td className="p-3"><div className="font-medium">{file.source_path}</div><div className="mt-1 mono text-[10px] text-muted-foreground">{file.media_type}</div></td><td className="p-3">{file.format_key}</td><td className="p-3">{file.processor_kind}</td><td className="p-3"><Status value={file.status} /></td><td className="max-w-md p-3 text-[11px] text-muted-foreground">{summary(file.warnings)}{file.missing_dependencies?.length ? <div className="mt-1 text-caution">Missing: {summary(file.missing_dependencies)}</div> : null}{file.last_error && <div className="mt-1 text-negative">{file.last_error}</div>}</td></tr>)}</tbody></table></div></section>
    {structure.data && <RobotViewer jobId={jobId} data={structure.data} />}{structure.error && !(structure.error instanceof ApiError && structure.error.status === 404) && <p className="text-xs text-negative">Robot viewer: {message(structure.error)}</p>}
    <section className="surface-card mt-5 p-3"><div className="section-title mb-2">Processing history</div><ol className="space-y-2">{job.data.events.map((event, index) => <li key={String(event.id ?? index)} className="flex gap-3 text-[11px]"><span className="mono w-12 shrink-0 text-muted-foreground">{String(event.progress_percent ?? "—")}%</span><span>{String(event.message ?? event.event_type ?? "Import event")}</span></li>)}</ol></section>
  </main>;
}

function RobotViewer({ jobId, data }: { jobId: string; data: Awaited<ReturnType<typeof importJobsApi.structure>> }) {
  const client = useQueryClient(); const [notes, setNotes] = useState<Record<string, string>>({}); const roots = useMemo(() => data.links.filter((link) => !link.parent_link_name), [data.links]);
  const review = async (candidateId: string, decision: "confirmed" | "rejected", classification?: "purchasable" | "fabricated") => { try { await importJobsApi.reviewCandidate(jobId, candidateId, { decision, classification, notes: notes[candidateId] }); await client.invalidateQueries({ queryKey: ["robot-structure", jobId] }); } catch (error) { toast({ title: "Candidate review failed", description: message(error), variant: "destructive" }); } };
  return <section className="surface-card p-4"><div className="mb-3 flex items-center gap-2"><Boxes className="h-4 w-4 text-primary" /><div><div className="section-title">Interactive robot structure</div><p className="text-[11px] text-muted-foreground">{data.links.length} links · {data.joints.length} joints. Links are structural entities, not assumed purchasable parts.</p></div></div><div className="grid gap-4 lg:grid-cols-2"><div className="rounded border border-border p-3"><h2 className="mb-2 text-sm font-semibold">Hierarchy</h2><ul className="space-y-1 text-xs">{(roots.length ? roots : data.links).map((root) => <LinkBranch key={root.id} name={root.name} links={data.links} joints={data.joints} depth={0} />)}</ul></div><div><h2 className="mb-2 text-sm font-semibold">Component candidates</h2><div className="space-y-2">{data.candidates.length === 0 && <p className="text-xs text-muted-foreground">No component candidates were inferred.</p>}{data.candidates.map((candidate) => <article key={candidate.id} className="rounded border border-border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div className="font-medium text-xs">{candidate.candidate_name}</div><span className="badge-neutral">{candidate.review_status}</span></div><p className="mt-1 text-[11px] text-muted-foreground">Suggested {candidate.classification} · {Math.round(Number(candidate.confidence) * 100)}% confidence</p><input aria-label={`Notes for ${candidate.candidate_name}`} value={notes[candidate.id] ?? candidate.notes ?? ""} onChange={(event) => setNotes((value) => ({ ...value, [candidate.id]: event.target.value }))} placeholder="Annotation" className="input-bare mt-2 min-h-10 w-full" /><div className="mt-2 flex flex-wrap gap-2"><button onClick={() => void review(candidate.id, "confirmed", "purchasable")} className="btn-primary btn-sm min-h-10">Confirm purchasable</button><button onClick={() => void review(candidate.id, "confirmed", "fabricated")} className="btn-ghost btn-sm min-h-10">Mark fabricated</button><button onClick={() => void review(candidate.id, "rejected")} className="btn-ghost btn-sm min-h-10">Reject</button></div></article>)}</div></div></div></section>;
}

function LinkBranch({ name, links, joints, depth }: { name: string; links: Array<Record<string, unknown> & { id: string; name: string; parent_link_name?: string | null; mass_kg?: number | null }>; joints: Array<Record<string, unknown> & { child_link_name?: string | null; parent_link_name?: string | null; joint_type: string }>; depth: number }) { const link = links.find((item) => item.name === name); const children = links.filter((item) => item.parent_link_name === name); const parentJoint = joints.find((joint) => joint.child_link_name === name); return <li><details open={depth < 2}><summary className="min-h-8 cursor-pointer rounded px-2 py-1 hover:bg-muted"><span className="font-medium">{name}</span>{parentJoint && <span className="ml-2 text-[10px] text-muted-foreground">{parentJoint.joint_type} joint</span>}{link?.mass_kg != null && <span className="ml-2 mono text-[10px]">{String(link.mass_kg)} kg</span>}</summary>{children.length > 0 && <ul className="ml-4 border-l border-border pl-2">{children.map((child) => <LinkBranch key={child.id} name={child.name} links={links} joints={joints} depth={depth + 1} />)}</ul>}</details></li>; }
function Status({ value }: { value: string }) { const good = ["complete", "ready", "confirmed", "verified"].includes(value); const bad = ["failed", "rejected", "unsupported"].includes(value); return <span className={good ? "pill pill-good" : bad ? "pill pill-bad" : "badge-neutral"}>{value.replaceAll("_", " ")}</span>; }
function State({ children }: { children: React.ReactNode }) { return <main className="mx-auto flex min-h-[50vh] max-w-2xl flex-col items-center justify-center gap-3 px-4 text-center">{children}</main>; }
function summary(value: unknown): string { if (!Array.isArray(value) || value.length === 0) return "None"; return value.map((item) => typeof item === "string" ? item : JSON.stringify(item)).join(" · "); }
function message(error: unknown): string { return error instanceof Error ? error.message : "Unexpected error."; }
function kindFor(name: string): FileKind { const extension = name.split(".").at(-1)?.toLowerCase(); if (["urdf", "xacro", "sdf", "srdf"].includes(extension ?? "")) return "urdf"; if (["mjcf"].includes(extension ?? "")) return "mjcf"; if (["step", "stp", "stl", "obj", "gltf", "glb", "dae", "iges", "igs", "usd", "usdz"].includes(extension ?? "")) return "cad"; if (["csv", "tsv", "xlsx"].includes(extension ?? "")) return "bom"; if (["yaml", "yml", "toml"].includes(extension ?? "")) return "configuration"; if (["pdf", "md", "xml", "json"].includes(extension ?? "")) return "document"; return "other"; }
