import { Link } from "react-router-dom";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Brain, Loader2, Trash2 } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "@/hooks/use-toast";
import { improvementApi } from "@/lib/api/systems";

export default function ImprovementRecords() {
  const { user, loading } = useAuth(); const client = useQueryClient(); const records = useQuery({ queryKey: ["ai-improvement-records", user?.id], queryFn: ({ signal }) => improvementApi.list(signal), enabled: Boolean(user) });
  const remove = async (id: string) => { if (!window.confirm("Delete this improvement record and withdraw its retained context?")) return; try { await improvementApi.remove(id); await client.invalidateQueries({ queryKey: ["ai-improvement-records"] }); toast({ title: "Improvement record deleted" }); } catch (error) { toast({ title: "Could not delete record", description: message(error), variant: "destructive" }); } };
  if (loading) return <State><Loader2 className="h-5 w-5 animate-spin" /> Loading account…</State>;
  if (!user) return <State><Brain className="h-7 w-7 text-primary" /><h1 className="text-xl font-bold">Sign in to inspect AI improvement records</h1><Link to="/auth?next=%2Fsettings%2Fai-improvement" className="btn-primary">Sign in</Link></State>;
  return <main className="mx-auto max-w-5xl px-4 py-6"><div className="mb-4"><div className="section-title">Privacy and AI</div><h1 className="text-[22px] font-bold">Your AI improvement records</h1><p className="mt-1 max-w-3xl text-xs text-muted-foreground">These structured records capture corrections, failures, undo events, and unavailable information. Secrets and full source files are not retained here. Deleting a record removes its sanitized context and withdraws consent.</p></div>
    <section className="surface-card overflow-hidden">{records.isLoading && <div className="p-5 text-sm text-muted-foreground">Loading records…</div>}{records.error && <div className="p-5 text-sm text-negative">{message(records.error)}</div>}{records.data?.items.length === 0 && <div className="p-8 text-center text-sm text-muted-foreground">No AI improvement records are stored for your account.</div>}<div className="divide-y divide-border">{records.data?.items.map((item) => <article key={item.id} className="p-3"><div className="flex flex-wrap items-start justify-between gap-2"><div><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-semibold">{item.category.replaceAll("_", " ")}</span><span className="badge-neutral">{item.resolution_status}</span></div><p className="mt-1 text-xs text-muted-foreground">{item.feature} · {new Date(item.created_at).toLocaleString()}</p></div><button onClick={() => void remove(item.id)} className="btn-ghost btn-sm min-h-10 text-negative"><Trash2 className="h-3.5 w-3.5" /> Delete</button></div>{item.sanitized_context && <pre className="mt-3 max-h-48 overflow-auto rounded bg-muted p-2 text-[10px]">{JSON.stringify(item.sanitized_context, null, 2)}</pre>}<dl className="mt-2 grid gap-2 text-[10px] text-muted-foreground sm:grid-cols-3"><div><dt>Privacy</dt><dd className="font-medium text-foreground">{String(item.privacy_state ?? "private")}</dd></div><div><dt>Consent</dt><dd className="font-medium text-foreground">{String(item.consent_state ?? "operational only")}</dd></div><div><dt>Model</dt><dd className="font-medium text-foreground">{String(item.model_key ?? "not recorded")}</dd></div></dl></article>)}</div></section>
  </main>;
}
function State({ children }: { children: React.ReactNode }) { return <main className="mx-auto flex min-h-[50vh] max-w-2xl flex-col items-center justify-center gap-3 px-4 text-center">{children}</main>; }
function message(error: unknown): string { return error instanceof Error ? error.message : "Unexpected error."; }
