import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Bell, Check, FileQuestion, Loader2, X } from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { RichTechnicalEditor } from "@/components/common/RichTechnicalEditor";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "@/hooks/use-toast";
import { projectSystemsApi } from "@/lib/api/systems";

export default function InformationGap() { const { id = "" } = useParams<{ id: string }>(); const { user } = useAuth(); const client = useQueryClient(); const [body, setBody] = useState(""); const [sources, setSources] = useState(""); const [busy, setBusy] = useState(false); const gap = useQuery({ queryKey: ["information-gap", id], queryFn: ({ signal }) => projectSystemsApi.informationGap(id, signal), enabled: Boolean(id), retry: false });
  const refresh = () => client.invalidateQueries({ queryKey: ["information-gap", id] }); const respond = async () => { setBusy(true); try { await projectSystemsApi.respondToInformationGap(id, { responseText: body, sources: sources.split(/\r?\n/gu).map((url) => url.trim()).filter(Boolean).map((url) => ({ url })), fileIds: [] }); setBody(""); setSources(""); await refresh(); toast({ title: "Response submitted for review" }); } catch (error) { toast({ title: "Response failed", description: message(error), variant: "destructive" }); } finally { setBusy(false); } }; const review = async (responseId: string, decision: "approve" | "reject") => { try { await projectSystemsApi.reviewInformationResponse(responseId, decision); await refresh(); toast({ title: decision === "approve" ? "Response approved and added to project knowledge" : "Response rejected" }); } catch (error) { toast({ title: "Review failed", description: message(error), variant: "destructive" }); } };
  if (gap.isLoading) return <State><Loader2 className="h-5 w-5 animate-spin" /> Loading information request…</State>; if (gap.error || !gap.data) return <State>{message(gap.error)}</State>; const item = gap.data.item;
  return <main className="mx-auto max-w-4xl px-4 py-6"><Link to="/projects" className="text-xs text-muted-foreground hover:text-foreground">Projects</Link><section className="surface-card mt-3 p-4"><div className="flex items-start gap-3"><FileQuestion className="mt-0.5 h-5 w-5 shrink-0 text-caution" /><div><div className="section-title">Structured missing-information request</div><h1 className="mt-1 text-xl font-bold">{item.question}</h1><span className="mt-2 inline-block badge-neutral">{item.status}</span></div></div><dl className="mt-4 grid gap-3 sm:grid-cols-2"><div><dt className="text-[10px] uppercase text-muted-foreground">Why a reliable answer is unavailable</dt><dd className="mt-1 text-xs">{item.reliability_reason}</dd></div><div><dt className="text-[10px] uppercase text-muted-foreground">Missing information</dt><dd className="mt-1 text-xs">{item.missing_fields?.join(", ") || "Not itemized"}</dd></div><div className="sm:col-span-2"><dt className="text-[10px] uppercase text-muted-foreground">Suggested sources</dt><dd className="mt-1 text-xs">{item.suggested_sources?.join(" · ") || "No source was suggested."}</dd></div></dl>{user && <button onClick={async () => { try { await projectSystemsApi.subscribeToInformationGap(id); toast({ title: "Subscribed to resolution updates" }); } catch (error) { toast({ title: "Subscription failed", description: message(error), variant: "destructive" }); } }} className="btn-ghost btn-sm mt-3 min-h-10"><Bell className="h-4 w-4" /> Notify me when resolved</button>}</section>
    <section className="surface-card mt-4 overflow-hidden"><div className="border-b border-border p-3 section-title">Community and maintainer responses</div><div className="divide-y divide-border">{gap.data.responses.map((response) => <article key={response.id} className="p-4"><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-xs font-semibold">{response.responder_name || response.responder_username || "Contributor"}</span><span className="badge-neutral">{response.status}</span></div><div className="prose prose-sm mt-3 max-w-none text-xs dark:prose-invert"><ReactMarkdown remarkPlugins={[remarkGfm]} skipHtml>{response.response_text}</ReactMarkdown></div>{response.sources?.length ? <ul className="mt-2 text-[10px] text-muted-foreground">{response.sources.map((source, index) => <li key={index}>{String(source.url ?? source.label ?? JSON.stringify(source))}</li>)}</ul> : null}{response.status === "submitted" && <div className="mt-3 flex gap-2"><button onClick={() => void review(response.id, "approve")} className="btn-primary btn-sm min-h-10"><Check className="h-4 w-4" /> Approve</button><button onClick={() => void review(response.id, "reject")} className="btn-ghost btn-sm min-h-10"><X className="h-4 w-4" /> Reject</button></div>}</article>)}{gap.data.responses.length === 0 && <p className="p-6 text-center text-xs text-muted-foreground">No responses yet.</p>}</div></section>
    {user ? <section className="surface-card mt-4 p-4"><h2 className="text-sm font-semibold">Respond with evidence</h2><p className="mt-1 text-[11px] text-muted-foreground">A maintainer reviews responses before adding them to the project knowledge base.</p><div className="mt-3"><RichTechnicalEditor value={body} onChange={setBody} label="Response" autosaveKey={`gap-response-${id}`} maxLength={40_000} minRows={7} /></div><label className="mt-3 block text-xs">Source links (one per line)<textarea value={sources} onChange={(event) => setSources(event.target.value)} rows={3} className="input-bare mt-1 h-auto min-h-24 w-full resize-y" /></label><button disabled={busy || body.trim().length < 4} onClick={() => void respond()} className="btn-primary mt-3 min-h-11 disabled:opacity-50">Submit response</button></section> : <p className="mt-4 text-center text-xs"><Link to={`/auth?next=${encodeURIComponent(`/information-gaps/${id}`)}`} className="text-primary">Sign in</Link> to respond.</p>}
  </main>; }
function State({ children }: { children: React.ReactNode }) { return <main className="mx-auto flex min-h-[50vh] max-w-2xl flex-col items-center justify-center gap-3 px-4 text-center">{children}</main>; }
function message(error: unknown): string { return error instanceof Error ? error.message : "Unexpected error."; }
