import { FileText, Scale, ShieldCheck, Users } from "lucide-react";
import { Link } from "react-router-dom";

const LAST_UPDATED = "July 22, 2026";
const PRIVACY_EMAIL = "privacy@robopartpicker.com";
const SUPPORT_EMAIL = "support@robopartpicker.com";

type LegalDocument = "overview" | "terms" | "privacy" | "guidelines";

const nav: Array<{ kind: Exclude<LegalDocument, "overview">; label: string; to: string }> = [
  { kind: "terms", label: "Terms of Service", to: "/terms" },
  { kind: "privacy", label: "Privacy Policy", to: "/privacy" },
  { kind: "guidelines", label: "Community Guidelines", to: "/community-guidelines" },
];

export default function Legal({ document = "overview" }: { document?: LegalDocument }) {
  if (document === "overview") return <LegalOverview />;
  return <DocumentShell document={document}>{document === "terms" ? <Terms /> : document === "privacy" ? <Privacy /> : <Guidelines />}</DocumentShell>;
}

function LegalOverview() {
  return <main className="mx-auto max-w-[1000px] px-4 py-8">
    <div className="section-title">Trust centre</div>
    <h1 className="mt-1 text-2xl font-bold">Legal, privacy, and community safety</h1>
    <p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">Plain-language information about using RoboPartPicker, how account and project data are handled, and the standards expected in technical collaboration and marketplace activity.</p>
    <div className="mt-6 grid gap-3 md:grid-cols-3">
      <LegalCard icon={Scale} title="Terms of Service" text="Rules for accounts, technical content, RPPS releases, marketplace activity, AI features, and platform availability." to="/terms" />
      <LegalCard icon={ShieldCheck} title="Privacy Policy" text="What information is collected, why it is used, when it is public, service providers, retention, and your choices." to="/privacy" />
      <LegalCard icon={Users} title="Community Guidelines" text="Evidence standards, respectful collaboration, marketplace integrity, messaging safety, and prohibited conduct." to="/community-guidelines" />
    </div>
    <section className="surface-card mt-6 p-4"><h2 className="text-sm font-semibold">Important engineering notice</h2><p className="mt-2 text-xs leading-5 text-muted-foreground">Robotics work can involve high voltage, heavy machinery, stored energy, sharp tools, heat, moving mechanisms, radio systems, and autonomous behaviour. Project records, community posts, supplier observations, price estimates, and AI output are informational. They are not certification, professional engineering advice, or a guarantee that a design is safe, compatible, available, or fit for your use.</p></section>
  </main>;
}

function DocumentShell({ document, children }: { document: Exclude<LegalDocument, "overview">; children: React.ReactNode }) {
  const current = nav.find((item) => item.kind === document)!;
  return <main className="mx-auto max-w-[1000px] px-4 py-8">
    <div className="section-title">RoboPartPicker legal</div>
    <div className="mt-1 flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">{current.label}</h1><p className="mt-1 text-xs text-muted-foreground">Effective and last updated: {LAST_UPDATED}</p></div><Link to="/legal" className="btn-ghost btn-sm"><FileText className="h-3.5 w-3.5" /> Legal overview</Link></div>
    <nav aria-label="Legal documents" className="my-5 flex gap-2 overflow-x-auto border-y border-border py-2">{nav.map((item) => <Link key={item.kind} to={item.to} aria-current={item.kind === document ? "page" : undefined} className={item.kind === document ? "btn-primary btn-sm whitespace-nowrap" : "btn-ghost btn-sm whitespace-nowrap"}>{item.label}</Link>)}</nav>
    <article className="legal-document surface-card p-5 sm:p-7">{children}</article>
  </main>;
}

function Terms() {
  return <>
    <Lead>These Terms of Service form an agreement between you and the operator of RoboPartPicker (“RoboPartPicker,” “we,” “us”). By creating an account or using the service, you agree to these Terms and the <LinkText to="/community-guidelines">Community Guidelines</LinkText>. If you do not agree, do not use the service.</Lead>
    <Section title="1. Eligibility and accounts"><P>You must be at least 13 and able to provide meaningful consent to use an account. If you are under the age of majority where you live, a parent or guardian must approve your use. You must be the age of majority to create marketplace listings, make offers, or arrange transactions.</P><P>Provide accurate account information, protect your credentials, and notify us if you suspect unauthorized access. You are responsible for activity performed through your account unless caused by our failure to use reasonable safeguards.</P></Section>
    <Section title="2. What RoboPartPicker provides"><P>RoboPartPicker provides tools for discovering components and projects, creating bills of materials and build records, publishing RPPS releases, importing technical files, collaborating, messaging, using assisted workflows, and posting marketplace information. Features, availability, data sources, and limits may change as the service develops.</P></Section>
    <Section title="3. Technical and safety information"><P>Robotics involves real physical risk. Content on the service may be incomplete, outdated, incorrect, or unsuitable for your design. Verify dimensions, ratings, revisions, compatibility, licensing, safety requirements, supplier terms, and test results independently. Follow applicable laws, codes, manufacturer instructions, and qualified professional advice.</P><P>Labels such as “verified,” “reproduced,” or “compatible” describe recorded evidence under the platform’s rules; they are not regulatory approval, certification, a warranty, or a substitute for your own validation.</P></Section>
    <Section title="4. Your content and project visibility"><P>You retain ownership of content you submit. You grant us a worldwide, non-exclusive, royalty-free licence to host, process, reproduce, display, and distribute that content only as needed to operate, secure, improve, and provide the service according to the visibility and collaboration settings you choose.</P><P>You must have the rights needed to upload or publish your content. Do not submit trade secrets, export-controlled material, credentials, personal information about others without authority, or content that infringes intellectual-property or privacy rights. Public and unlisted content can be copied by others; deleting it may not remove copies or immutable release snapshots already lawfully created.</P></Section>
    <Section title="5. RPPS releases and third-party licences"><P>The RoboPartPicker Project Standard (RPPS) is a draft interchange format, not an established industry standard. Publishing an RPPS release creates a versioned technical record but does not transfer ownership of referenced CAD, software, documentation, or component data. You remain responsible for accurate authorship, attribution, and licence declarations.</P></Section>
    <Section title="6. Marketplace"><P>RoboPartPicker is a venue for user-provided listings, wanted requests, estimates, and messages. We do not currently process payments, hold funds, take title to goods, act as broker, guarantee identity or condition, or become a party to a transaction. Buyers and sellers are responsible for due diligence, lawful goods, taxes, shipping, insurance, returns, warranties, and their final agreement.</P><P>Price estimates and comparable records are informational ranges, not appraisals or guaranteed sale values. Do not move forward if a counterparty asks for unsafe payment methods, credentials, or activity that violates law or these Terms.</P></Section>
    <Section title="7. AI-assisted features"><P>AI output may contain errors or unsupported inferences. Review previews, sources, changed fields, confidence, and missing information before applying anything. High-impact actions require your explicit confirmation, but confirmation does not make the output correct. Do not rely on AI alone for safety, compatibility, pricing, legal, medical, financial, or professional engineering decisions.</P></Section>
    <Section title="8. Acceptable use"><P>You must follow the <LinkText to="/community-guidelines">Community Guidelines</LinkText>. You may not abuse the service, evade access controls, scrape or overload systems contrary to published interfaces, introduce malware, impersonate others, manipulate evidence or reviews, spam users, facilitate illegal transactions, or use the service to harm people or property.</P></Section>
    <Section title="9. Moderation and termination"><P>We may remove content, restrict features, suspend accounts, preserve relevant records, or report conduct when reasonably necessary to enforce these Terms, protect users, comply with law, or secure the service. Where appropriate, we will provide notice and an appeal path. You may stop using the service and request account deletion, subject to legal obligations and records that must be retained for security, disputes, or immutable public history.</P></Section>
    <Section title="10. Service and warranty disclaimer"><P>The service is provided “as is” and “as available.” To the extent permitted by law, we disclaim implied warranties of merchantability, fitness for a particular purpose, non-infringement, accuracy, availability, and uninterrupted operation. Nothing in these Terms limits rights or warranties that cannot legally be excluded.</P></Section>
    <Section title="11. Limitation of liability"><P>To the extent permitted by law, RoboPartPicker and its operator will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for loss of profits, data, goodwill, opportunity, or property arising from use of the service, technical information, user content, AI output, marketplace activity, or third-party services. Our aggregate liability for claims relating to the service will not exceed the greater of CAD $100 and the amount you paid us during the 12 months before the event giving rise to the claim. These limits do not apply where prohibited by law.</P></Section>
    <Section title="12. Governing law and disputes"><P>These Terms are governed by the laws of Ontario and the federal laws of Canada applicable there, without regard to conflict-of-law rules. Courts located in Ontario have jurisdiction, except where consumer law gives you the right to bring a claim elsewhere. Before filing a claim, contact us so we can try to resolve it informally.</P></Section>
    <Section title="13. Changes and contact"><P>We may update these Terms for legal, security, or product reasons. Material changes will be highlighted in the service before they take effect when reasonably possible. Continued use after the effective date means you accept the updated Terms.</P><P>Questions about these Terms: <Email address={SUPPORT_EMAIL} />.</P></Section>
  </>;
}

function Privacy() {
  return <>
    <Lead>This policy explains how RoboPartPicker collects, uses, discloses, and protects personal information. The short version: we collect what is needed to run the technical collaboration platform, distinguish public from private records, do not sell personal information, and do not currently use targeted advertising.</Lead>
    <div className="mb-6 grid gap-2 sm:grid-cols-3"><Summary title="You control visibility" text="Projects, builds, files, and organizations carry explicit visibility settings." /><Summary title="AI is contextual" text="Only the context needed for an invoked AI action is sent to the configured provider." /><Summary title="No payment cards" text="The marketplace does not currently process payments or store card details." /></div>
    <Section title="1. Information we collect"><P><Strong>Account and profile information:</Strong> name, email address, authentication records, username, avatar, organization membership, preferences, and account security events.</P><P><Strong>Content and collaboration:</Strong> projects, RPPS releases, BOMs, builds, technical records, files, imports, evidence, comments, messages, reports, marketplace listings, offers, and associated metadata and version history.</P><P><Strong>Usage and device information:</Strong> request identifiers, IP-derived security and coarse country information, browser and device details, timestamps, referring category, feature events, error records, and abuse-prevention signals. Creator analytics use privacy-reduced aggregates and rotating identifiers where implemented.</P><P><Strong>AI interactions:</Strong> prompts, selected project or build context, previews, applied or rejected changes, model and prompt versions, tool calls, latency, cost, and structured correction or friction records. Improvement records use sanitized context and are separated from operational records.</P><P><Strong>Imported sources:</Strong> repository URLs, public metadata, uploaded archives and files, provenance, parser output, and processing warnings. Imported scripts and robot-description content are treated as untrusted and are not executed in the Worker.</P></Section>
    <Section title="2. Why we use information"><List items={["Provide accounts, authentication, projects, builds, uploads, collaboration, messaging, marketplace, search, imports, and support.", "Preserve version history, attribution, provenance, evidence, and user-requested public releases.", "Route and audit contextual AI actions, obtain confirmation, support undo, measure cost, and improve opted-in workflows.", "Secure the service, prevent spam and abuse, investigate reports, enforce policies, debug failures, and meet legal obligations.", "Produce privacy-reduced product and creator analytics and improve usability and reliability."]} /></Section>
    <Section title="3. What becomes public"><P>Your username, display name, avatar, role, and content may be public when attached to a public project, release, build, technical record, community post, or marketplace listing. Reproduction attribution is shown only when the associated build is public; private builds contribute only anonymous aggregate counts. Unlisted content is accessible to anyone with its link. Private and organization content is limited by the selected access controls.</P><P>Before publishing, review files for personal information, credentials, proprietary material, location data, or identifying metadata. Public release snapshots and contributions may remain in version history to preserve integrity and attribution.</P></Section>
    <Section title="4. When information is shared"><P>We share information with service providers only as needed to operate the service, including Cloudflare for hosting, D1, R2, queues, security, and network delivery; configured email delivery providers; configured AI model providers when you invoke an AI feature; and public source hosts such as GitHub when you request an import. Providers may process information in Canada, the United States, or other countries where they operate, subject to their safeguards and local law.</P><P>We may also disclose information with your direction, to organization collaborators according to roles, to investigate abuse or security incidents, in a business transfer, or when required or permitted by law. We do not sell personal information.</P></Section>
    <Section title="5. Consent and choices"><P>Core account and operational processing is necessary to provide the service you request. Optional processing—such as retaining sanitized AI improvement records—uses a separate preference where available. You can change project/build visibility, notification preferences, messaging settings, and AI improvement choices in the product. You can inspect and delete eligible AI improvement records at <LinkText to="/settings/ai-improvement">AI improvement records</LinkText>.</P><P>You may withdraw consent to optional processing. Withdrawing from processing required to operate an account may require account deletion and does not invalidate processing already lawfully completed.</P></Section>
    <Section title="6. Cookies and local storage"><P>RoboPartPicker currently uses essential cookies and browser storage for secure sessions, OAuth flows, interface preferences, and similar requested functions. We do not currently use advertising cookies. If non-essential tracking is introduced, this policy and the consent experience must be updated before it is enabled where consent is required.</P></Section>
    <Section title="7. Retention"><P>We retain information only as long as reasonably needed for the purposes above, including account operation, version and attribution integrity, security, dispute resolution, and legal obligations. Retention varies by record: session and security logs are shorter-lived; active account and project records remain while needed; public immutable releases and accepted contributions may remain as historical records. Deleted records may persist temporarily in encrypted backups before expiry.</P></Section>
    <Section title="8. Security"><P>We use measures appropriate to the information, including same-origin secure sessions, authorization checks, scoped roles, upload controls, rate limits, audit records, encryption in transit, and Cloudflare platform safeguards. No online system is completely secure. Do not upload credentials or secrets; report suspected compromise promptly.</P></Section>
    <Section title="9. Access, correction, and deletion"><P>Subject to applicable law, you may request access to personal information we hold about you, ask for corrections, challenge our handling, withdraw optional consent, or request deletion. We may need to verify your identity and may retain information where law, security, disputes, or public version integrity require it. Start with in-product controls or email the Privacy Officer at <Email address={PRIVACY_EMAIL} />.</P></Section>
    <Section title="10. Children"><P>The service is not directed to children under 13, and we do not knowingly collect their personal information. A parent or guardian should contact us if they believe a child under 13 provided personal information. Marketplace activity is limited to users who have reached the age of majority where they live.</P></Section>
    <Section title="11. Changes, questions, and complaints"><P>We will update this policy when practices change and highlight material changes when reasonably possible. Questions, access requests, or complaints may be sent to the Privacy Officer at <Email address={PRIVACY_EMAIL} />. You may also contact the <a href="https://www.priv.gc.ca/" target="_blank" rel="noreferrer" className="text-primary hover:underline">Office of the Privacy Commissioner of Canada</a> or the privacy regulator in your province.</P></Section>
  </>;
}

function Guidelines() {
  return <>
    <Lead>RoboPartPicker is for practical, evidence-aware robotics collaboration. These guidelines apply to projects, builds, technical records, comments, messages, organizations, AI-assisted submissions, and marketplace activity.</Lead>
    <Section title="1. Be constructive and specific"><List items={["Discuss the work, not the person. Harassment, threats, hate, doxxing, stalking, and sexual exploitation are prohibited.", "Use clear titles, relevant context, units, versions, and reproducible steps. Avoid repetitive posts, unsolicited promotion, and message spam.", "Respect blocks, message-request decisions, contributor boundaries, and organization roles."]} /></Section>
    <Section title="2. Separate facts, claims, and inference"><List items={["Cite sources for specifications, compatibility, safety, availability, pricing, and performance claims.", "Label estimates, AI-generated drafts, anecdotal results, suspected identities, and unverified BOMs honestly.", "Do not fabricate tests, reproductions, reviews, comparable sales, supplier relationships, certifications, or evidence.", "Correct material errors and preserve the original record where version history or review integrity requires it."]} /></Section>
    <Section title="3. Treat safety as part of the design"><List items={["Call out hazardous voltage, current, stored energy, heat, pressure, pinch/crush zones, sharp tools, lifting, batteries, autonomous motion, radio emissions, and required protective equipment.", "Do not encourage bypassing guards, interlocks, legal requirements, manufacturer limits, or competent review.", "Report a safety concern through the reporting tools and provide the smallest evidence needed to evaluate it."]} /></Section>
    <Section title="4. Protect privacy, security, and intellectual property"><List items={["Do not post credentials, private keys, access tokens, personal addresses, private communications, or sensitive files.", "Do not upload material you lack permission to share. Preserve author, licence, source, and fork attribution.", "Security research must avoid unauthorized access, persistence, data collection, disruption, or public disclosure that creates immediate risk. Report vulnerabilities privately to support."]} /></Section>
    <Section title="5. Marketplace integrity"><List items={["Describe ownership, identity, revision, condition, modifications, missing items, test evidence, and known defects accurately.", "Do not list illegal, stolen, recalled, counterfeit, dangerously misrepresented, or rights-infringing items.", "Do not manipulate prices, reviews, availability, comparable records, or sold inventory. Estimates are not guaranteed values.", "Keep negotiation respectful and use payment, shipping, and identity-verification practices appropriate to the risk. RoboPartPicker does not currently process payments or guarantee transactions."]} /></Section>
    <Section title="6. Enforcement and appeals"><P>Users can report content, messages, listings, or conduct. Depending on severity and history, we may add warnings, limit distribution, remove content, restrict messaging or marketplace access, suspend accounts, preserve evidence, or notify appropriate authorities. Good-faith technical disagreement is not a violation. Where appropriate, affected users may request review through <Email address={SUPPORT_EMAIL} />.</P></Section>
  </>;
}

function LegalCard({ icon: Icon, title, text, to }: { icon: typeof Scale; title: string; text: string; to: string }) {
  return <Link to={to} className="surface-card surface-card-hover p-4"><Icon className="h-5 w-5 text-primary" /><h2 className="mt-3 text-sm font-semibold">{title}</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">{text}</p><span className="mt-3 inline-block text-[11px] font-medium text-primary">Read document →</span></Link>;
}

function Lead({ children }: { children: React.ReactNode }) { return <p className="mb-6 border-l-2 border-primary pl-4 text-sm leading-6">{children}</p>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mt-6 first:mt-0"><h2 className="text-base font-semibold">{title}</h2><div className="mt-2 space-y-2">{children}</div></section>; }
function P({ children }: { children: React.ReactNode }) { return <p className="text-xs leading-5 text-muted-foreground">{children}</p>; }
function Strong({ children }: { children: React.ReactNode }) { return <strong className="font-semibold text-foreground">{children}</strong>; }
function List({ items }: { items: string[] }) { return <ul className="list-disc space-y-1.5 pl-5 text-xs leading-5 text-muted-foreground">{items.map((item) => <li key={item}>{item}</li>)}</ul>; }
function LinkText({ to, children }: { to: string; children: React.ReactNode }) { return <Link to={to} className="text-primary hover:underline">{children}</Link>; }
function Email({ address }: { address: string }) { return <a href={`mailto:${address}`} className="text-primary hover:underline">{address}</a>; }
function Summary({ title, text }: { title: string; text: string }) { return <div className="rounded border border-border bg-muted/20 p-3"><div className="text-xs font-semibold">{title}</div><p className="mt-1 text-[10.5px] leading-4 text-muted-foreground">{text}</p></div>; }
