import { useEffect, useState } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, Ban, Flag, Loader2, MessageCircle, Send } from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { RichTechnicalEditor } from "@/components/common/RichTechnicalEditor";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "@/hooks/use-toast";
import { uploadFile } from "@/lib/api/files";
import { messagesApi } from "@/lib/api/systems";

export default function Messages() {
  const { conversationId } = useParams<{ conversationId: string }>(); const { user, loading } = useAuth();
  if (loading) return <State><Loader2 className="h-5 w-5 animate-spin" /> Loading messages…</State>;
  if (!user) return <State><MessageCircle className="h-7 w-7 text-primary" /><h1 className="text-xl font-bold">Sign in to use direct messages</h1><Link to={`/auth?next=${encodeURIComponent(conversationId ? `/messages/${conversationId}` : "/messages")}`} className="btn-primary">Sign in</Link></State>;
  return conversationId ? <Conversation id={conversationId} userId={user.id} /> : <Inbox />;
}

function Inbox() {
  const [params] = useSearchParams(); const navigate = useNavigate(); const target = params.get("to"); const [initial, setInitial] = useState(""); const [busy, setBusy] = useState(false);
  const inbox = useQuery({ queryKey: ["messages"], queryFn: ({ signal }) => messagesApi.list(signal), refetchInterval: 15_000 });
  const start = async () => { if (!target) return; setBusy(true); try { const result = await messagesApi.create({ recipientUserId: target, contextType: (params.get("context") as "project" | "build" | "marketplace" | "general" | null) ?? "general", contextId: params.get("contextId") ?? undefined, message: initial.trim() || undefined }); navigate(`/messages/${result.id}`); } catch (error) { toast({ title: "Message request failed", description: message(error), variant: "destructive" }); } finally { setBusy(false); } };
  return <main className="mx-auto max-w-5xl px-4 py-6"><div className="mb-4"><div className="section-title">Collaboration</div><h1 className="text-[22px] font-bold">Messages</h1><p className="text-xs text-muted-foreground">Message requests, project and marketplace context, spam controls, reporting, and privacy settings are enforced server-side.</p></div>
    {target && <section className="surface-card mb-4 p-4"><h2 className="text-sm font-semibold">New message request</h2><p className="mt-1 text-[11px] text-muted-foreground">The recipient can accept or decline. Their contact policy may limit requests.</p><div className="mt-3"><RichTechnicalEditor value={initial} onChange={setInitial} label="Introductory message" autosaveKey={`message-request-${target}`} maxLength={20_000} minRows={5} /></div><button disabled={busy} onClick={() => void start()} className="btn-primary mt-3 min-h-10"><Send className="h-4 w-4" /> Send request</button></section>}
    <section className="surface-card overflow-hidden"><div className="border-b border-border p-3 section-title">Inbox and requests</div>{inbox.isLoading && <div className="p-5 text-sm text-muted-foreground">Loading conversations…</div>}{inbox.error && <div className="p-5 text-sm text-negative">{message(inbox.error)}</div>}{inbox.data?.items.length === 0 && <div className="p-8 text-center text-sm text-muted-foreground">No conversations yet. Contact a project owner, maintainer, builder, or seller from their associated record.</div>}<div className="divide-y divide-border">{inbox.data?.items.map((item) => <Link key={item.id} to={`/messages/${item.id}`} className="grid gap-2 p-3 hover:bg-muted/50 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="truncate text-sm font-semibold">{item.other_name || item.other_username || "RoboPartPicker user"}</span>{item.status === "requested" && <span className="pill pill-warn">request</span>}{Number(item.unread_count) > 0 && <span className="badge-neutral">{item.unread_count} unread</span>}</div><p className="mt-1 truncate text-xs text-muted-foreground">{item.last_message ?? "No message text"}</p><p className="mt-1 text-[10px] text-muted-foreground">{item.context_type}{item.context_id ? ` · ${item.context_id}` : ""}</p></div><time className="text-[10px] text-muted-foreground">{item.last_message_at ? new Date(item.last_message_at).toLocaleString() : "New"}</time></Link>)}</div></section>
  </main>;
}

function Conversation({ id, userId }: { id: string; userId: string }) {
  const client = useQueryClient(); const [body, setBody] = useState(""); const [attachment, setAttachment] = useState<File | null>(null); const [busy, setBusy] = useState(false); const detail = useQuery({ queryKey: ["message", id], queryFn: ({ signal }) => messagesApi.get(id, signal), refetchInterval: 10_000 });
  useEffect(() => { const node = document.getElementById("message-end"); node?.scrollIntoView({ block: "nearest" }); }, [detail.data?.messages.length]);
  const refresh = async () => Promise.all([client.invalidateQueries({ queryKey: ["message", id] }), client.invalidateQueries({ queryKey: ["messages"] })]);
  const respond = async (accept: boolean) => { setBusy(true); try { await messagesApi.respond(id, accept); await refresh(); } catch (error) { toast({ title: "Could not update request", description: message(error), variant: "destructive" }); } finally { setBusy(false); } };
  const send = async () => { if (!body.trim()) return; setBusy(true); try { let attachmentFileId: string | undefined; if (attachment) { const uploaded = await uploadFile(attachment, "attachment"); if (uploaded.status !== "ready") throw new Error("Attachment did not pass upload validation."); attachmentFileId = uploaded.fileId; } const result = await messagesApi.send(id, body.trim(), attachmentFileId) as { status?: string }; setBody(""); setAttachment(null); await refresh(); if (result.status === "quarantined") toast({ title: "Message held for moderator review", description: "Automated safety checks flagged this message." }); } catch (error) { toast({ title: "Message failed", description: message(error), variant: "destructive" }); } finally { setBusy(false); } };
  if (detail.isLoading) return <State><Loader2 className="h-5 w-5 animate-spin" /> Loading conversation…</State>;
  if (detail.error || !detail.data) return <State>{message(detail.error)}</State>;
  const other = detail.data.participants.find((item) => item.user_id !== userId); const pending = detail.data.membership.role === "recipient" && detail.data.membership.request_status === "pending"; const active = detail.data.item.status === "active" && detail.data.membership.request_status === "accepted";
  const report = async () => { const reason = window.prompt("Why are you reporting this conversation?"); if (!reason?.trim()) return; try { await messagesApi.report(id, reason.trim()); toast({ title: "Report submitted" }); } catch (error) { toast({ title: "Report failed", description: message(error), variant: "destructive" }); } };
  const block = async () => { if (!other || !window.confirm(`Block ${other.name || other.username || "this user"}? This closes active conversations.`)) return; try { await messagesApi.block(other.user_id); await refresh(); toast({ title: "User blocked" }); } catch (error) { toast({ title: "Block failed", description: message(error), variant: "destructive" }); } };
  return <main className="mx-auto flex min-h-[calc(100vh-160px)] max-w-5xl flex-col px-3 py-4 sm:px-4"><header className="mb-3 flex flex-wrap items-center justify-between gap-2"><div className="flex min-w-0 items-center gap-2"><Link to="/messages" aria-label="Back to messages" className="btn-ghost min-h-10 min-w-10 p-2"><ArrowLeft className="h-4 w-4" /></Link><div className="min-w-0"><h1 className="truncate text-sm font-bold">{other?.name || other?.username || "Conversation"}</h1><p className="truncate text-[10px] text-muted-foreground">{String(detail.data.item.context_type)}{detail.data.item.context_id ? ` · ${detail.data.item.context_id}` : ""} · {String(detail.data.item.status)}</p></div></div><div className="flex gap-1"><button onClick={() => void report()} className="btn-ghost btn-sm min-h-10"><Flag className="h-3.5 w-3.5" /> Report</button><button onClick={() => void block()} className="btn-ghost btn-sm min-h-10 text-negative"><Ban className="h-3.5 w-3.5" /> Block</button></div></header>
    {pending && <div className="mb-3 rounded border border-caution/40 bg-caution/5 p-3"><p className="text-xs">This is a message request. Accept it before replying.</p><div className="mt-2 flex gap-2"><button disabled={busy} onClick={() => void respond(true)} className="btn-primary min-h-10">Accept</button><button disabled={busy} onClick={() => void respond(false)} className="btn-ghost min-h-10">Decline</button></div></div>}
    <section aria-label="Conversation messages" className="surface-card min-h-0 flex-1 overflow-y-auto p-3"><div className="space-y-3">{detail.data.messages.map((item) => { const mine = item.sender_user_id === userId; return <article key={item.id} className={`flex ${mine ? "justify-end" : "justify-start"}`}><div className={`max-w-[88%] rounded-lg border p-3 sm:max-w-[72%] ${mine ? "border-primary/30 bg-primary/10" : "border-border bg-background"}`}><div className="prose prose-sm max-w-none text-xs dark:prose-invert"><ReactMarkdown remarkPlugins={[remarkGfm]} skipHtml>{item.body_markdown}</ReactMarkdown></div>{item.attachment_file_id && <a href={`/api/v1/files/${item.attachment_file_id}/content`} className="mt-2 inline-block text-[11px] text-primary">View attachment</a>}<div className="mt-1 text-right text-[9px] text-muted-foreground">{new Date(item.created_at).toLocaleString()} · {item.status}</div></div></article>; })}<div id="message-end" /></div></section>
    {active && <section className="sticky bottom-0 mt-3 rounded border border-border bg-background p-2 shadow-lg"><RichTechnicalEditor value={body} onChange={setBody} label="Reply" autosaveKey={`message-${id}`} maxLength={20_000} minRows={4} className="min-h-28" /><div className="mt-2 flex flex-wrap items-center justify-between gap-2"><label className="text-[11px]"><span className="sr-only">Attachment</span><input type="file" accept="image/png,image/jpeg,image/webp,image/gif,application/pdf,text/plain" onChange={(event) => setAttachment(event.target.files?.[0] ?? null)} className="max-w-[220px] text-[10px]" /></label><button disabled={busy || !body.trim()} onClick={() => void send()} className="btn-primary min-h-10 disabled:opacity-50"><Send className="h-4 w-4" /> Send</button></div></section>}
  </main>;
}

function State({ children }: { children: React.ReactNode }) { return <main className="mx-auto flex min-h-[50vh] max-w-2xl flex-col items-center justify-center gap-3 px-4 text-center">{children}</main>; }
function message(error: unknown): string { return error instanceof Error ? error.message : "Unexpected error."; }
