import { useState } from "react";
import { Link } from "react-router-dom";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, Loader2, LockKeyhole, RefreshCw, ShieldCheck } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "@/hooks/use-toast";
import { api } from "@/lib/api/client";
import { operationsApi } from "@/lib/api/systems";

const queueLabels: Record<string, string> = { imports: "Import jobs", bomVerifications: "BOM verification", messagingReports: "Messaging abuse", communityReports: "Community moderation", marketplaceReports: "Marketplace moderation", aiFriction: "AI friction", dataSources: "Data-source health", evaluations: "AI evaluations", aiCost: "AI cost" };

export default function Operations() {
  const { user, loading } = useAuth(); const client = useQueryClient(); const [tab, setTab] = useState<"queues" | "cases" | "ai">("queues");
  const overview = useQuery({ queryKey: ["operations-overview"], queryFn: ({ signal }) => operationsApi.overview(signal), enabled: Boolean(user), retry: false });
  const queues = useQuery({ queryKey: ["operations-queues"], queryFn: ({ signal }) => operationsApi.queues(signal), enabled: Boolean(user), retry: false });
  const cases = useQuery({ queryKey: ["operations-cases"], queryFn: ({ signal }) => operationsApi.cases(signal), enabled: Boolean(user), retry: false });
  const aiConfig = useQuery({ queryKey: ["admin-ai-config"], queryFn: ({ signal }) => api.get<{ providers: Array<Record<string, unknown>>; models: Array<Record<string, unknown>>; rules: Array<Record<string, unknown>>; prompts: Array<Record<string, unknown>> }>("/api/v1/admin/ai/config", { signal, retry: false }), enabled: Boolean(user), retry: false });
  const aiEvaluations = useQuery({ queryKey: ["admin-ai-evaluations"], queryFn: ({ signal }) => api.get<{ suites: Array<Record<string, unknown>>; runs: Array<Record<string, unknown>> }>("/api/v1/admin/ai/evaluations", { signal, retry: false }), enabled: Boolean(user), retry: false });
  if (loading) return <State><Loader2 className="h-5 w-5 animate-spin" /> Loading account…</State>;
  if (!user) return <State><LockKeyhole className="h-7 w-7 text-primary" /><h1 className="text-xl font-bold">Protected operations</h1><Link to="/auth?next=%2Fadmin%2Foperations" className="btn-primary">Sign in</Link></State>;
  if (overview.error) return <State><ShieldCheck className="h-7 w-7 text-negative" /><h1 className="text-xl font-bold">Operations access required</h1><p className="text-sm text-muted-foreground">{message(overview.error)}</p></State>;
  const refresh = () => {
    void Promise.all([
      client.invalidateQueries({ queryKey: ["operations-overview"] }),
      client.invalidateQueries({ queryKey: ["operations-queues"] }),
      client.invalidateQueries({ queryKey: ["operations-cases"] }),
      client.invalidateQueries({ queryKey: ["admin-ai-config"] }),
      client.invalidateQueries({ queryKey: ["admin-ai-evaluations"] }),
    ]);
  };
  return <main className="mx-auto max-w-[1280px] px-4 py-6"><div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><div className="section-title">Protected administration</div><h1 className="text-[22px] font-bold">Operations console</h1><p className="text-xs text-muted-foreground">Live operational queues, moderation, model routing, evaluations, cost, sources, appeals, and audit-backed resolution.</p></div><button onClick={refresh} className="btn-ghost btn-sm min-h-10"><RefreshCw className="h-4 w-4" /> Refresh</button></div>
    <div className="mb-5 grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-6">{Object.entries(overview.data ?? {}).filter(([, value]) => typeof value === "number").map(([key, value]) => <div key={key} className="surface-card p-3"><div className="text-[10px] uppercase text-muted-foreground">{human(key)}</div><div className="mt-1 mono text-lg font-bold">{Number(value).toLocaleString()}</div></div>)}</div>
    <nav className="mb-3 flex gap-1 overflow-x-auto border-b border-border pb-2">{(["queues", "cases", "ai"] as const).map((item) => <button key={item} onClick={() => setTab(item)} className={tab === item ? "btn-primary btn-sm min-h-10" : "btn-ghost btn-sm min-h-10"}>{item === "ai" ? "AI routing & evaluations" : human(item)}</button>)}</nav>
    {tab === "queues" && <div className="grid gap-4 xl:grid-cols-2">{Object.entries(queues.data ?? {}).map(([key, items]) => <Queue key={key} title={queueLabels[key] ?? human(key)} items={items} />)}</div>}
    {tab === "cases" && <section className="surface-card overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-muted/50 text-[10px] uppercase text-muted-foreground"><tr><th className="p-3">Case</th><th className="p-3">Type</th><th className="p-3">Priority</th><th className="p-3">Status</th><th className="p-3">Created</th></tr></thead><tbody>{cases.data?.items.map((item) => <tr key={item.id} className="border-t border-border"><td className="p-3 font-medium">{item.title}</td><td className="p-3">{human(item.case_type)}</td><td className="p-3">{item.priority}</td><td className="p-3"><select className="input-bare min-h-10" value={item.status} onChange={async (event) => { try { await operationsApi.updateCase(item.id, { status: event.target.value }); await client.invalidateQueries({ queryKey: ["operations-cases"] }); } catch (error) { toast({ title: "Case update failed", description: message(error), variant: "destructive" }); } }}><option value="open">Open</option><option value="triaged">Triaged</option><option value="assigned">Assigned</option><option value="investigating">Investigating</option><option value="resolved">Resolved</option><option value="dismissed">Dismissed</option><option value="appealed">Appealed</option></select></td><td className="p-3 text-muted-foreground">{new Date(item.created_at).toLocaleString()}</td></tr>)}</tbody></table></div></section>}
    {tab === "ai" && <div className="space-y-4">{aiConfig.error && <div className="surface-card p-4 text-sm text-caution">Administrator role is required to modify model routing. Moderator operational queues remain available.</div>}{aiConfig.data && <><div className="grid gap-4 lg:grid-cols-2"><Queue title="Provider registry" items={aiConfig.data.providers} /><Queue title="Model registry" items={aiConfig.data.models} /><Queue title="Routing rules" items={aiConfig.data.rules} /><Queue title="Prompt versions" items={aiConfig.data.prompts} /></div><p className="rounded border border-primary/30 bg-primary/5 p-3 text-xs">Candidate prompt versions and routing rules cannot be activated until a passing regression evaluation is recorded. No provider is encoded as permanently cheapest or best.</p></>}{aiEvaluations.data && <div className="grid gap-4 lg:grid-cols-2"><Queue title="Versioned evaluation suites" items={aiEvaluations.data.suites} /><Queue title="Regression runs" items={aiEvaluations.data.runs} /></div>}</div>}
  </main>;
}

function Queue({ title, items }: { title: string; items: Array<Record<string, unknown>> }) { return <section className="surface-card overflow-hidden"><div className="flex items-center justify-between border-b border-border p-3"><span className="section-title">{title}</span><span className="badge-neutral">{items.length}</span></div><div className="max-h-[420px] divide-y divide-border overflow-y-auto">{items.length === 0 && <p className="p-5 text-xs text-muted-foreground">Queue is empty.</p>}{items.slice(0, 200).map((item, index) => <article key={String(item.id ?? index)} className="p-3"><div className="flex items-center gap-2"><Activity className="h-3.5 w-3.5 shrink-0 text-primary" /><span className="truncate text-xs font-medium">{String(item.title ?? item.name ?? item.task_type ?? item.source_path ?? item.id ?? "Record")}</span>{item.status != null && <span className="badge-neutral shrink-0">{String(item.status)}</span>}</div><div className="mt-1 flex flex-wrap gap-x-3 text-[10px] text-muted-foreground">{["category", "priority", "provider_key", "model_key", "current_stage", "created_at"].filter((key) => item[key] != null).map((key) => <span key={key}>{human(key)}: {String(item[key])}</span>)}</div></article>)}</div></section>; }
function State({ children }: { children: React.ReactNode }) { return <main className="mx-auto flex min-h-[50vh] max-w-2xl flex-col items-center justify-center gap-3 px-4 text-center">{children}</main>; }
function human(value: string): string { return value.replace(/([a-z])([A-Z])/gu, "$1 $2").replaceAll("_", " ").replace(/^./u, (char) => char.toUpperCase()); }
function message(error: unknown): string { return error instanceof Error ? error.message : "Unexpected error."; }
