import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, FileQuestion, FlaskConical, Loader2, Plus } from "lucide-react";
import { ContextualAiActions } from "@/components/ai/ContextualAiActions";
import { RichTechnicalEditor } from "@/components/common/RichTechnicalEditor";
import { toast } from "@/hooks/use-toast";
import { projectSystemsApi } from "@/lib/api/systems";
import { getProjectBySlug } from "@/lib/projects";

const recordTypes = ["test_result", "calibration", "measurement", "integration_result", "substitution_result", "failure", "resolution", "configuration_snapshot", "firmware_snapshot", "assembly_checkpoint", "supplier_outcome", "safety_check"] as const;

export default function ProjectKnowledge() {
  const { slug = "" } = useParams<{ slug: string }>(); const client = useQueryClient(); const [mode, setMode] = useState<"browse" | "record" | "gap">("browse");
  const project = useQuery({ queryKey: ["project", slug], queryFn: () => getProjectBySlug(slug), enabled: Boolean(slug) }); const records = useQuery({ queryKey: ["project-records", project.data?.id], queryFn: ({ signal }) => projectSystemsApi.technicalRecords(project.data!.id, signal), enabled: Boolean(project.data?.id), retry: false }); const gaps = useQuery({ queryKey: ["project-gaps", project.data?.id], queryFn: ({ signal }) => projectSystemsApi.missingInformation(project.data!.id, signal), enabled: Boolean(project.data?.id), retry: false });
  if (project.isLoading) return <State><Loader2 className="h-5 w-5 animate-spin" /> Loading project…</State>;
  if (project.error || !project.data) return <State>{project.error ? message(project.error) : "Project not found."}</State>;
  const refresh = async () => Promise.all([client.invalidateQueries({ queryKey: ["project-records", project.data!.id] }), client.invalidateQueries({ queryKey: ["project-gaps", project.data!.id] })]);
  return <main className="mx-auto max-w-6xl px-4 py-5"><Link to={`/projects/${project.data.slug}`} className="mb-3 inline-flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground"><ArrowLeft className="h-3.5 w-3.5" /> {project.data.name}</Link><div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><div className="section-title">Grounded project knowledge</div><h1 className="text-[22px] font-bold">Technical records and information gaps</h1><p className="max-w-3xl text-xs text-muted-foreground">Searchable test evidence, measurements, configurations, failures, and approved resolutions are available to the project-scoped assistant.</p></div><div className="flex gap-2"><button onClick={() => setMode(mode === "record" ? "browse" : "record")} className="btn-primary min-h-10"><FlaskConical className="h-4 w-4" /> Add record</button><button onClick={() => setMode(mode === "gap" ? "browse" : "gap")} className="btn-ghost min-h-10"><FileQuestion className="h-4 w-4" /> Request information</button></div></div>
    {mode === "record" && <TechnicalRecordForm projectId={project.data.id} onSaved={async () => { await refresh(); setMode("browse"); }} />}{mode === "gap" && <GapForm projectId={project.data.id} onSaved={async () => { await refresh(); setMode("browse"); }} />}
    <div className="mt-4 grid gap-4 lg:grid-cols-[minmax(0,1.35fr)_minmax(300px,0.65fr)]"><section className="surface-card overflow-hidden"><div className="flex items-center justify-between border-b border-border p-3"><span className="section-title">Build evidence / technical records</span><span className="badge-neutral">{records.data?.items.length ?? 0}</span></div>{records.error && <p className="p-4 text-xs text-negative">{message(records.error)}</p>}<div className="divide-y divide-border">{records.data?.items.map((item) => <article key={item.id} className="p-3"><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-semibold">{item.title}</span><span className="badge-neutral">{item.record_type.replaceAll("_", " ")}</span><span className="badge-neutral">{item.verification_state.replaceAll("_", " ")}</span></div><p className="mt-2 whitespace-pre-wrap text-xs text-muted-foreground">{item.result_text}</p><div className="mt-2 flex flex-wrap gap-3 text-[10px] text-muted-foreground"><span>Confidence {Math.round(Number(item.confidence) * 100)}%</span><span>{new Date(item.created_at).toLocaleString()}</span><span>Reproductions {String(item.reproduction_count ?? 0)}</span></div></article>)}{records.data?.items.length === 0 && <p className="p-6 text-center text-xs text-muted-foreground">No technical records yet.</p>}</div></section>
      <section className="surface-card self-start overflow-hidden"><div className="flex items-center justify-between border-b border-border p-3"><span className="section-title">Missing information</span><span className="badge-neutral">{gaps.data?.items.length ?? 0}</span></div>{gaps.error && <p className="p-4 text-xs text-negative">{message(gaps.error)}</p>}<div className="divide-y divide-border">{gaps.data?.items.map((item) => <Link key={item.id} to={`/information-gaps/${item.id}`} className="block p-3 hover:bg-muted/50"><div className="flex items-center justify-between gap-2"><h2 className="text-xs font-semibold">{item.question}</h2><span className="badge-neutral">{item.status}</span></div><p className="mt-1 text-[11px] text-muted-foreground">Why unresolved: {item.reliability_reason}</p>{item.missing_fields?.length ? <p className="mt-2 text-[10px]">Missing: {item.missing_fields.join(", ")}</p> : null}<p className="mt-2 text-[10px] text-muted-foreground">{item.response_count} response{Number(item.response_count) === 1 ? "" : "s"}</p></Link>)}{gaps.data?.items.length === 0 && <p className="p-6 text-center text-xs text-muted-foreground">No open information gaps.</p>}</div></section></div>
  </main>;
}

function TechnicalRecordForm({ projectId, onSaved }: { projectId: string; onSaved: () => Promise<void> }) { const [recordType, setRecordType] = useState<(typeof recordTypes)[number]>("test_result"); const [title, setTitle] = useState(""); const [method, setMethod] = useState(""); const [result, setResult] = useState(""); const [confidence, setConfidence] = useState(0.5); const [busy, setBusy] = useState(false); const current = { title, methodText: method, resultNotes: result }; const aiApply = (values: Record<string, unknown>) => { if (typeof values.title === "string") setTitle(values.title); if (typeof values.methodText === "string") setMethod(values.methodText); if (typeof values.resultNotes === "string") setResult(values.resultNotes); if (typeof values.observedText === "string") setResult(values.observedText); };
  const save = async () => { setBusy(true); try { await projectSystemsApi.createTechnicalRecord({ recordType, projectId, title, method: method || undefined, resultText: result, confidence, visibility: "private", conditions: {}, measurements: [], evidence: [], fileIds: [], reproductionCount: 0, verificationState: "unverified" }); await onSaved(); toast({ title: "Technical record saved" }); } catch (error) { toast({ title: "Record could not be saved", description: message(error), variant: "destructive" }); } finally { setBusy(false); } };
  return <section className="surface-card border-primary/30 p-4"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-sm font-semibold">New technical record</h2><p className="text-[11px] text-muted-foreground">Private by default. Verification and publication are separate review steps.</p></div><ContextualAiActions form="build_record" current={current} onApply={aiApply} projectId={projectId} surface="technical-record" label="AI record actions" /></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs">Record type<select value={recordType} onChange={(event) => setRecordType(event.target.value as typeof recordType)} className="input-bare mt-1 min-h-11 w-full">{recordTypes.map((type) => <option key={type} value={type}>{type.replaceAll("_", " ")}</option>)}</select></label><label className="text-xs">Confidence: {Math.round(confidence * 100)}%<input type="range" min="0" max="1" step="0.05" value={confidence} onChange={(event) => setConfidence(Number(event.target.value))} className="mt-3 w-full" /></label></div><label className="mt-3 block text-xs">Title<input value={title} maxLength={300} onChange={(event) => setTitle(event.target.value)} className="input-bare mt-1 min-h-11 w-full" /></label><div className="mt-3"><RichTechnicalEditor value={method} onChange={setMethod} label="Method and conditions" autosaveKey={`technical-method-${projectId}`} maxLength={20_000} minRows={5} /></div><div className="mt-3"><RichTechnicalEditor value={result} onChange={setResult} label="Result and evidence summary" autosaveKey={`technical-result-${projectId}`} maxLength={40_000} minRows={7} /></div><button disabled={busy || title.trim().length < 2 || !result.trim()} onClick={() => void save()} className="btn-primary mt-3 min-h-11 disabled:opacity-50"><Plus className="h-4 w-4" /> Save record</button></section>; }

function GapForm({ projectId, onSaved }: { projectId: string; onSaved: () => Promise<void> }) { const [question, setQuestion] = useState(""); const [reason, setReason] = useState(""); const [fields, setFields] = useState(""); const [sources, setSources] = useState(""); const [busy, setBusy] = useState(false); const save = async () => { setBusy(true); try { await projectSystemsApi.createMissingInformation(projectId, { question, reliabilityReason: reason, missingFields: split(fields), suggestedSources: split(sources), visibility: "project" }); await onSaved(); toast({ title: "Information request created", description: "Interested project members can respond and will be notified after an approved resolution." }); } catch (error) { toast({ title: "Request could not be created", description: message(error), variant: "destructive" }); } finally { setBusy(false); } };
  return <section className="surface-card border-caution/40 p-4"><h2 className="text-sm font-semibold">Structured missing-information request</h2><p className="mt-1 text-[11px] text-muted-foreground">State exactly what is missing and why the current evidence cannot support a reliable answer.</p><label className="mt-3 block text-xs">Question<input value={question} onChange={(event) => setQuestion(event.target.value)} className="input-bare mt-1 min-h-11 w-full" /></label><div className="mt-3"><RichTechnicalEditor value={reason} onChange={setReason} label="Why this cannot be answered reliably" autosaveKey={`gap-reason-${projectId}`} maxLength={4_000} minRows={5} /></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-xs">Missing fields (one per line)<textarea value={fields} onChange={(event) => setFields(event.target.value)} rows={4} className="input-bare mt-1 h-auto min-h-28 w-full resize-y" /></label><label className="text-xs">Suggested files or sources (one per line)<textarea value={sources} onChange={(event) => setSources(event.target.value)} rows={4} className="input-bare mt-1 h-auto min-h-28 w-full resize-y" /></label></div><button disabled={busy || question.trim().length < 4 || reason.trim().length < 4} onClick={() => void save()} className="btn-primary mt-3 min-h-11 disabled:opacity-50"><FileQuestion className="h-4 w-4" /> Create request</button></section>; }
function split(value: string): string[] { return value.split(/\r?\n|,/gu).map((item) => item.trim()).filter(Boolean); }
function State({ children }: { children: React.ReactNode }) { return <main className="mx-auto flex min-h-[50vh] max-w-2xl flex-col items-center justify-center gap-3 px-4 text-center">{children}</main>; }
function message(error: unknown): string { return error instanceof Error ? error.message : "Unexpected error."; }
