import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Boxes, DollarSign, Loader2, PackagePlus } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "@/hooks/use-toast";
import { partOutApi } from "@/lib/api/systems";

const presence = ["unconfirmed", "present", "missing", "modified", "damaged", "fabricated", "unidentifiable", "sold", "excluded"] as const;

export default function PartOutEditor() { const { id } = useParams<{ id: string }>(); const { user, loading } = useAuth(); if (loading) return <State><Loader2 className="h-5 w-5 animate-spin" /> Loading…</State>; if (!user) return <State><Boxes className="h-7 w-7 text-primary" /><Link to={`/auth?next=${encodeURIComponent(id ? `/marketplace/part-outs/${id}` : "/marketplace/part-outs")}`} className="btn-primary">Sign in</Link></State>; return id ? <Editor id={id} /> : <Index />; }

function Index() { const navigate = useNavigate(); const [sourceBuildId, setSourceBuildId] = useState(""); const [sourceBomVersionId, setSourceBomVersionId] = useState(""); const [sourceProjectId, setSourceProjectId] = useState(""); const [sourceListingId, setSourceListingId] = useState(""); const [currency, setCurrency] = useState("USD"); const [busy, setBusy] = useState(false); const list = useQuery({ queryKey: ["part-outs"], queryFn: ({ signal }) => partOutApi.list(signal) }); const create = async () => { setBusy(true); try { const result = await partOutApi.create({ sourceBuildId: sourceBuildId || undefined, sourceBomVersionId: sourceBomVersionId || undefined, sourceProjectId: sourceProjectId || undefined, sourceListingId: sourceListingId || undefined, currency }); navigate(`/marketplace/part-outs/${result.id}`); } catch (error) { toast({ title: "Part-out workflow could not be created", description: message(error), variant: "destructive" }); } finally { setBusy(false); } };
  return <main className="mx-auto max-w-6xl px-4 py-6"><div className="mb-4"><div className="section-title">Marketplace · robot part-out</div><h1 className="text-[22px] font-bold">Robot inventory and part-out workflows</h1><p className="max-w-3xl text-xs text-muted-foreground">Generate inventory from an exact build or BOM version, confirm every item, compare complete-robot and part-out estimates, then create editable draft listings.</p></div><section className="surface-card mb-5 p-4"><h2 className="text-sm font-semibold">Start from a build or BOM version</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="Build ID" value={sourceBuildId} onChange={setSourceBuildId} /><Field label="BOM version ID" value={sourceBomVersionId} onChange={setSourceBomVersionId} /><Field label="Project ID (optional provenance)" value={sourceProjectId} onChange={setSourceProjectId} /><Field label="Complete robot listing ID (optional)" value={sourceListingId} onChange={setSourceListingId} /><label className="text-xs">Currency<input value={currency} maxLength={3} onChange={(event) => setCurrency(event.target.value.toUpperCase())} className="input-bare mt-1 min-h-11 w-full" /></label></div><p className="mt-2 text-[10px] text-muted-foreground">If any part is sold, a connected complete-robot listing is automatically withdrawn so sold inventory cannot remain included.</p><button disabled={busy || (!sourceBuildId && !sourceBomVersionId)} onClick={() => void create()} className="btn-primary mt-3 min-h-11 disabled:opacity-50"><PackagePlus className="h-4 w-4" /> Create inventory</button></section><section className="surface-card overflow-hidden"><div className="border-b border-border p-3 section-title">Your part-outs</div><div className="divide-y divide-border">{list.data?.items.map((item) => <Link key={item.id} to={`/marketplace/part-outs/${item.id}`} className="grid gap-2 p-3 hover:bg-muted/50 sm:grid-cols-[1fr_auto] sm:items-center"><div><span className="mono text-xs">{item.id}</span><p className="mt-1 text-[10px] text-muted-foreground">{String(item.item_count ?? 0)} items · {String(item.sold_count ?? 0)} sold · {item.currency}</p></div><span className="badge-neutral">{item.status}</span></Link>)}{list.data?.items.length === 0 && <p className="p-6 text-center text-xs text-muted-foreground">No part-out workflows yet.</p>}</div></section></main>; }

function Editor({ id }: { id: string }) { const client = useQueryClient(); const [values, setValues] = useState<Record<string, { status: string; condition: string; price: string }>>({}); const [selected, setSelected] = useState<string[]>([]); const [busy, setBusy] = useState<string | null>(null); const detail = useQuery({ queryKey: ["part-out", id], queryFn: ({ signal }) => partOutApi.get(id, signal), refetchInterval: 15_000 }); useEffect(() => { if (!detail.data) return; setValues((current) => { const next = { ...current }; for (const item of detail.data.items) if (!next[item.id]) { const pricing = item.pricing as Record<string, unknown> | undefined; next[item.id] = { status: item.presence_status, condition: item.condition_grade ?? "untested", price: pricing?.askingMinor ? (Number(pricing.askingMinor) / 100).toFixed(2) : "" }; } return next; }); }, [detail.data]); const refresh = () => client.invalidateQueries({ queryKey: ["part-out", id] });
  const save = async (itemId: string) => { const value = values[itemId]; setBusy(itemId); try { await partOutApi.updateItem(id, itemId, { presenceStatus: value.status, conditionGrade: value.condition || null, testEvidence: [], pricing: value.price ? { askingMinor: Math.round(Number(value.price) * 100) } : {} }); await refresh(); } catch (error) { toast({ title: "Inventory update failed", description: message(error), variant: "destructive" }); } finally { setBusy(null); } }; const estimate = async () => { setBusy("estimate"); try { await partOutApi.estimate(id, { estimatedFeeRate: 0.13, shippingComplexity: "medium", ageAssumptionYears: null }); await refresh(); } catch (error) { toast({ title: "Estimate unavailable", description: message(error), variant: "destructive" }); } finally { setBusy(null); } }; const drafts = async () => { setBusy("drafts"); try { const created = await partOutApi.createDrafts(id, selected); await refresh(); setSelected([]); toast({ title: `${created.items.length} editable draft listing${created.items.length === 1 ? "" : "s"} created`, description: "Review each draft before publication." }); } catch (error) { toast({ title: "Draft generation failed", description: message(error), variant: "destructive" }); } finally { setBusy(null); } };
  if (detail.isLoading) return <State><Loader2 className="h-5 w-5 animate-spin" /> Loading inventory…</State>; if (detail.error || !detail.data) return <State>{message(detail.error)}</State>; return <main className="mx-auto max-w-[1280px] px-4 py-5"><Link to="/marketplace/part-outs" className="text-xs text-muted-foreground hover:text-foreground">All part-outs</Link><div className="mt-2 mb-4 flex flex-wrap items-end justify-between gap-3"><div><div className="section-title">Robot part-out workflow</div><h1 className="mono text-lg font-bold">{id}</h1><span className="mt-2 inline-block badge-neutral">{detail.data.item.status}</span></div><div className="flex flex-wrap gap-2"><button disabled={busy !== null} onClick={() => void estimate()} className="btn-ghost min-h-10"><DollarSign className="h-4 w-4" /> Generate estimates</button><button disabled={busy !== null || selected.length === 0} onClick={() => void drafts()} className="btn-primary min-h-10"><PackagePlus className="h-4 w-4" /> Create {selected.length || ""} drafts</button></div></div>
    <div className="mb-4 rounded border border-primary/30 bg-primary/5 p-3 text-xs">Estimates are evidence-based ranges, not guaranteed sale values. They show comparable records, condition and age assumptions, completeness, tests, fees, shipping complexity, confidence, and source freshness.</div><section className="surface-card overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-xs"><thead className="bg-muted/50 text-[10px] uppercase text-muted-foreground"><tr><th className="p-3">Draft</th><th className="p-3">Component</th><th className="p-3">Presence</th><th className="p-3">Condition</th><th className="p-3">Asking price</th><th className="p-3">Action</th></tr></thead><tbody>{detail.data.items.map((item) => { const value = values[item.id] ?? { status: item.presence_status, condition: item.condition_grade ?? "untested", price: "" }; const available = !["sold", "missing", "excluded"].includes(value.status) && !item.draft_listing_id; return <tr key={item.id} className="border-t border-border"><td className="p-3"><input aria-label={`Select ${item.description}`} type="checkbox" disabled={!available} checked={selected.includes(item.id)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, item.id] : current.filter((value) => value !== item.id))} />{item.draft_listing_id && <Link to={`/marketplace/${item.draft_listing_id}`} className="ml-2 text-primary">Open</Link>}</td><td className="p-3 font-medium">{item.description}</td><td className="p-3"><select value={value.status} onChange={(event) => setValues((current) => ({ ...current, [item.id]: { ...value, status: event.target.value } }))} className="input-bare min-h-10">{presence.map((status) => <option key={status} value={status}>{status.replaceAll("_", " ")}</option>)}</select></td><td className="p-3"><select value={value.condition} onChange={(event) => setValues((current) => ({ ...current, [item.id]: { ...value, condition: event.target.value } }))} className="input-bare min-h-10"><option value="A">A</option><option value="B">B</option><option value="C">C</option><option value="untested">Untested</option><option value="for_parts">For parts</option><option value="not_applicable">N/A</option></select></td><td className="p-3"><input type="number" min="0" step="0.01" value={value.price} onChange={(event) => setValues((current) => ({ ...current, [item.id]: { ...value, price: event.target.value } }))} className="input-bare min-h-10 w-28" /></td><td className="p-3"><button disabled={busy !== null} onClick={() => void save(item.id)} className="btn-ghost btn-sm min-h-10">{busy === item.id ? "Saving…" : "Save"}</button></td></tr>; })}</tbody></table></div></section>
    <section className="mt-4 grid gap-4 lg:grid-cols-2">{detail.data.estimates.map((estimate, index) => <article key={String(estimate.id ?? index)} className="surface-card p-4"><div className="flex items-center justify-between gap-2"><h2 className="text-sm font-semibold">{String(estimate.estimate_type).replaceAll("_", " ")}</h2><span className="badge-neutral">{Math.round(Number(estimate.confidence) * 100)}% confidence</span></div><p className="mt-2 mono text-lg font-bold">{money(Number(estimate.low_minor), String(estimate.currency))} – {money(Number(estimate.high_minor), String(estimate.currency))}</p><p className="text-xs">Expected {money(Number(estimate.expected_minor), String(estimate.currency))}</p><pre className="mt-3 max-h-40 overflow-auto rounded bg-muted p-2 text-[10px]">{JSON.stringify(estimate.assumptions, null, 2)}</pre><p className="mt-2 text-[10px] text-muted-foreground">Source freshness: {String(estimate.source_freshness_at ?? "No comparable date")} · {String(estimate.disclaimer)}</p></article>)}</section>
  </main>; }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="text-xs">{label}<input value={value} onChange={(event) => onChange(event.target.value)} className="input-bare mt-1 min-h-11 w-full" /></label>; }
function State({ children }: { children: React.ReactNode }) { return <main className="mx-auto flex min-h-[50vh] max-w-2xl flex-col items-center justify-center gap-3 px-4 text-center">{children}</main>; }
function money(minor: number, currency: string) { return new Intl.NumberFormat(undefined, { style: "currency", currency }).format(minor / 100); }
function message(error: unknown): string { return error instanceof Error ? error.message : "Unexpected error."; }
